#!/bin/sh
### BEGIN INIT INFO
# Provides:          mmgpio
# Required-Start:    networking $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO
#acima adptado vncserver e outros

NAME=mmgpio
LOGFILE=/var/log/mmgpio.log

. /lib/lsb/init-functions

start() {
  sleep 15

  if [ "$(sudo grep -wc "#host-name" /etc/avahi/avahi-daemon.conf)" -gt 0 ]
  then
    echo "Imagem não ativada, ative-a para utilizar este serviço."
  else

    sudo bash /home/mindmakers/programs/shells/mmgpio.sh &>>/var/log/mmgpio.log
    echo 'Starting service…' >&2
    sudo s3r &>>/var/log/mmgpio.log & echo \$!

    sleep 15
    if pgrep -f s3r > /dev/null
    then
      echo "$NAME is now running"
    else
      echo ''
      echo "Error! Could not start $NAME!"
      echo "trying again"
      sudo s3r &>>/var/log/mmgpio.log & echo \$!
    fi

  fi
}

stop() {
  echo 'Stopping service…' >&2
  sudo pkill s3r
  echo 'Service stopped' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|no] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    echo "Notice: log file was not removed: $LOGFILE" >&2
    update-rc.d -f $NAME remove
    rm -fv "$0"
  else
    echo "Abort!"
  fi
}

status() {
  if [ -z "$(ps axf | grep s3r | grep -v grep)" ]; then
    printf "%s\n" "The process appears to be dead" >&2
  else
    echo "sr3 appears to be running"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|status|uninstall|restart}"
esac

exit 0
