#Cria arquivos .log na máquina local em /home/mindmakers/debug de todos os:
#ansible_facts, pacotes instalados e suas versões.
- hosts: localhost

  tasks: 
  - name: Criando pastas de verificação
    file:
       path: /home/mindmakers/debug
       state: directory
       mode: 0755
  - local_action: copy content="{{ ansible_facts }}" dest="/home/mindmakers/debug/ansible_facts.log"
  - name: Verificando arquivos instalados
    command: apt list --installed
    register: apt_list
  - local_action: copy content="{{ apt_list.stdout_lines }}" dest="/home/mindmakers/debug/apt_list.log"
