# Arquivo playbook - imagem para Raspberry Pi Headless
- hosts: localhost
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
#    - include_vars: local-en.yml
#      when: p.stat.exists  
#  vars:
#     linguagem: "{{'en' if (p.stat.exists) else 'pt'}}"

  tasks:
    - name: Verifica versão do ansible.
      stat:
        path: /home/mindmakers/programs/verify/ansible27
      register: asb
    - include: tasks/ansibleupdate.yml
      when: not asb.stat.exists
    - name: verifica se diretorio Desktop existe.
      stat:
        path: /home/pi/Desktop
      register: p
    - include: tasks/copies-pt.yml
      when: not p.stat.exists
    - include: tasks/copies-en.yml
      when: p.stat.exists
    - include: tasks/copies.yml
    - include: tasks/packages.yml
    - include: tasks/packages-uninstall.yml
 #   - include: tasks/python.yml
    - include: tasks/3dslash.yml
    - include: tasks/hide-games.yml
    - include: tasks/install-extension.yml
 # Copia as notas de liberação e o atalho com nome da versão atualizados
    - include: tasks/final-version-copies-pt.yml
      when: not p.stat.exists
    - include: tasks/final-version-copies-en.yml
      when: p.stat.exists
 # Não acrescentar tarefas após estas últimas.
