# Arquivo playbook - imagem para Raspberry Pi Headless
- hosts: localhost
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - name: Verifica versão do ansible.
      stat:
        path: /home/mindmakers/programs/verify/ansible27
      register: ansb
    - include: tasks/ansibleupdate-headless.yml
      when: not ansb.stat.exists
    - name: verifica se diretorio Desktop existe.
      stat:
        path: /home/pi/Desktop
      register: p
    - include: tasks/copies-pt-headless.yml
      when: not p.stat.exists
    - include: tasks/copies-en-headless.yml
      when: p.stat.exists
    - include: tasks/tightvnc.yml
    - include: tasks/copies-headless.yml
    - include: tasks/packages-headless.yml
    - include: tasks/packages-uninstall-headless.yml
    - include: tasks/hide-games.yml
    - include: tasks/install-extension.yml
    - include: tasks/mblock.yml
    - include: tasks/apt-get.yml
 # Copia as notas de liberação e o atalho com nome da versão atualizados
    - include: tasks/final-version-copies-pt.yml
      when: not p.stat.exists
    - include: tasks/final-version-copies-en.yml
      when: p.stat.exists
 # Não acrescentar tarefas após estas últimas.
