- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
    - name: verifica se diretório Desktop existe como indicação de SO em inglês.
      stat:
        path: /home/pi/Desktop
      register: p 
#    - include_vars: local-en.yml
#      when: p.stat.exists  
  vars:
      linguagem: "{% if p.stat.exists %}'en'{% else %}'pt'{% endif %}"

  tasks:
    - include: tasks/copies.yml
    - include: tasks/copies-pt.yml
      when: linguagem == 'pt'
    - include: tasks/copies-en.yml
      when: linguagem == 'en'
    - include: tasks/packages.yml
