- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  vars:
    linguagem: pt 
  tasks:
    - include: tasks/copies.yml
    - include: tasks/copies-en.yml
      when: linguagem=='en'
    - include: tasks/copies-pt.yml
      when: linguagem=='pt'
    - include: tasks/packages.yml
