- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
    - name: verifica se diretório Desktop existe (usado como indicação de que o SO está em inglês).
      stat:
        path: /home/pi/Desktop
      register: p 
#    - include_vars: local-en.yml
#      when: p.stat.exists  
#  vars:
#     linguagem: "{{'en' if (p.stat.exists) else 'pt'}}"

  tasks:
    - include: tasks/copies.yml
    - include: tasks/copies-pt.yml
      when: not p.stat.exists
    - include: tasks/copies-en.yml
      when: p.stat.exists
    - include: tasks/packages.yml
