- hosts: localhost
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - name: Verificando versão do Ansible.
      stat:
        path: /home/mindmakers/programs/verify/ansible27
      register: ansb
    - include: tasks/ansibleupdate.yml
      when: not ansb.stat.exists
    - name: Verificando se diretório Desktop existe.
      stat:
        path: /home/pi/Desktop
      register: p
    - include: tasks/copies-pt.yml
      when: not p.stat.exists
    - include: tasks/copies-en.yml
      when: p.stat.exists
    - include: tasks/copies.yml
    - include: tasks/packages.yml
    - include: tasks/packages-uninstall.yml
    - include: tasks/3dslash.yml
    - include: tasks/hide-games.yml
    - include: tasks/install-extension.yml
    - include: tasks/mblock.yml
 # Copia as notas de liberação e o atalho com nome da versão atualizados
    - include: tasks/final-version-copies-pt.yml
      when: not p.stat.exists
    - include: tasks/final-version-copies-en.yml
      when: p.stat.exists
    - include: tasks/mblock.yml
# Não acrescentar tarefas após estas últimas.
