- hosts: localhost
  remote_user: root

  tasks:
    # - fail:
    #      msg: "Comando errado, se estiver tentando atualizar Chromebook, utilize o termo chomebook.yml ao final do comando"
    #   when: not ansible_facts.lsb.id == "Raspbian"
    - include: tasks/copies.yml
    - include: tasks/packages.yml
    - include: tasks/packages-uninstall.yml
    #- include: tasks/3dslash.yml
    - include: tasks/hide-games.yml
    - include: tasks/install-extension.yml
    - include: tasks/mt6.yml
    - include: tasks/apt-get.yml
    - include: tasks/rpimonitor.yml
    - include: tasks/avahi.yml
    - include: tasks/raspi-config.yml
