# Arquivo playbook complementar - imagem para do professor
- name: teste
  hosts: localhost
  tasks:
   - name: Verificando se diretório Desktop existe.
     stat:
        path: /home/pi/Desktop
     register: p
   - include: tasks/teacher-pt.yml
     when: not p.stat.exists
   - include: tasks/teacher-en.yml
     when: p.stat.exists
- import_playbook: student.yml

#  tasks:


#- name: Verificando se diretório Desktop existe.
#  stat:
#     path: /home/pi/Desktop
#  register: p
#- include: tasks/teacher-pt.yml
#  when: not p.stat.exists
#- import_task: tasks/teacher-en.yml
#  when: p.stat.exists
