# Arquivo playbook complementar - imagem para do professor
- hosts:               all
  remote_user:         root
  pre_tasks:
    - file:
        path:          /etc/apt/sources.list.d/rpimonitor.list
        state:         absent
    - apt:
         autoclean:    yes
    - name:            Atualizando Repositórios
      shell:           'sudo apt-get update --allow-releaseinfo-change'
      args:
        warn:          no
      when:            ansible_facts.lsb.codename == "buster"
    - apt:
         update_cache: yes
      changed_when:    False
      when:            not ansible_facts.lsb.codename == "buster"

  tasks:
    - set_fact:
        path2desktop:  "/home/pi/Desktop"
    - name:            Verificando se diretório Área de Trabalho existe
      stat:
        path:          "/home/pi/Área de Trabalho"
      register:        adt
    - set_fact:
        path2desktop:  "{{ adt.stat.path }}"
      when:            adt.stat.exists
    - include:         tasks/teacher-en.yml
    - include:         tasks/copies.yml
    - include:         tasks/packages.yml
    - include:         tasks/packages-uninstall.yml
    - include:         tasks/hide-games.yml
    - include:         tasks/install-extension.yml
    - include:         tasks/mt6.yml
    - include:         tasks/v3-6.yml
    - include:         tasks/v4-4-package-update.yml
    - include:         tasks/apt-get.yml
    #- include:        tasks/rpimonitor.yml
    - include:         tasks/avahi.yml
    - include:         tasks/raspi-config.yml


    - include:         tasks/copies-student.yml
    - include:         tasks/3dslash.yml
    - include:         tasks/sound-change-teacher.yml

# Copia as notas de liberação e o atalho com nome da versão atualizados
    - include:         tasks/final-version-copies-en.yml
    - include:         tasks/version_update.yml
    - include:         tasks/reboot.yml
# Não acrescentar tarefas após estas últimas.
