# Arquivo playbook complementar - imagem para do professor
- hosts: localhost

  tasks:
    - name:
      include: local.yml

    - name: Verificando se diretório Desktop existe.
      stat:
        path: /home/pi/Desktop
      register: p
    - include: tasks/teacher-pt.yml
      when: not p.stat.exists
    - include: tasks/teacher-en.yml
      when: p.stat.exists
      
