- hosts: localhost
  vars: 
    - linguagem: teste
  tasks:  
  - name: Verifica Linguagem OS
    shell: "env | grep LANG="
    register: shell_output
    
  - debug:
      var: shell_output.stdout_lines    
