- hosts: localhost
  become: true
  vars: 
    - linguagem: teste
  tasks:
  - name: Ansible grep pattern basic example
    shell: "env | grep LANG="
    register: shell_output
    set_fact: linguagem=shell_output.stdout_lines
    
  - name: Troca imagem de fundo
    shell: "pcmanfm --set-wallpaper=*fundo.png"
    args:
      chdir: "/home/mindmakers/"


  - debug:
      var: linguagem
