- hosts: localhost
  vars: 
    - ver: 6.9.0
  tasks:  
  - name: Verifica Versao npm
    shell: "npm --version"
#    shell: "npm --version |awk '{print $2}'"
#    shell: "echo npm --version"
    register: shell_output

#  - name: "This is bad version"
#    when: shell_output.stdout|strict=true("6.9.0")
  #  when: shell_output.stdout_lines != "6.9.0"
    


    
#  - name: "compara com 6.9.0"
#    register: n
#    when: shell_output.stdout == ver.value   #when ainda nao funcionou
#      - ansible_facts['shell_output.stdout_lines'] == "6.9.0"
#      - ansible_facts['distribution_major_version'] == "6"

# - name: Assertando  #quase funcionando
#    assert:
#      that:
#        - "{{ shell_output.stdout }}  == {{ ver }}" 
#        - "{{ shell_output.stdout }}  == 6.9.0"
#        - "{{ shell_output.stdout }}  == 6.9.0"
#    register: n

 
# - name: "Use set_fact to maybe change the variable you want"
#   set_fact: one_fact="{{ shell_output.stdout }}" other_fact="{{ ver }}"
#       register: n
 
    
  - debug:
      var: ver
#      assert:
#        that:
#          - shell_output.stdout_lines == ver
#        register: n
#    when: n.stat.exists
 
#  - debug:
#      var: shell_output.stdout_lines
#    when: assert= { that= "shell_output.stdout == '6.9.0'" }
    
#- name: after version 2.7 both 'msg' and 'fail_msg' can customize failing assertion message
#  assert:
#    that:
#      - "my_param <= 100"
#      - "my_param >= 0"
#   
#    success_msg: "'my_param' is between 0 and 100"
