- hosts: localhost
#  vars: 
#    - ver: 6.9.0
  tasks: 
#   - name: Testar raspi-config
#     include: tasks/raspi-config.yml
#  - name: instalar headless
#    include: tasks/headless.yml
  
  - name: Verifica Versao npm
    command: npm --version
    register: shell_output
  - local_action: copy content="{{ ansible_facts }}" dest="/home/mindmakers/ansible_facts"
  - name: Verifica arquivos instalados
    command: apt list --installed
    register: apt_list
  - local_action: copy content="{{ apt_list.stdout_lines }}" dest="/home/mindmakers/apt_list"
  
  
#  - local_action: 
#       copy content: "{{ansible_facts}}" 
#       dest: "/home/mindmakers/file"
 
    
#  - debug:
#      var: shell_output
#      assert:
#        that:
#          - shell_output.stdout_lines == ver
#        register: n
#    when: n.stat.exists
 
  - debug:
       var: apt_list
    when: shell_output is version('6.0', '>=')
    
#  - debug: 
#       var: ansible_facts
