- hosts: localhost
  vars: 
    - linguagem: teste
  tasks:  
  - name: Verifica Versao npm
    shell: "npm --version"
    register: shell_output
    
  - debug:
      var: shell_output.stdout_lines
    when: shell_output.stdout_lines = 6.9.0
