- hosts: localhost

  tasks:
    # - include: tasks/rpimonitor.yml
    - set_fact:
         path2desktop: "/home/pi/Desktop"
    - name: Verificando se diretório Área de Trabalho existe
      stat:
         path: "/home/pi/Área de Trabalho"
      register: adt
    - set_fact:
         path2desktop: "{{ adt.stat.path }}"
      when: adt.stat.exists
    - copy:
         src: files/classroom_test.desktop
         dest: "{{ path2desktop }}/classroom_test.desktop"
         owner: pi
         group: pi
         attributes: +i
         mode: 0755
    - lineinfile:
        path: "{{ path2desktop }}/classroom_test.desktop"
        regexp: '^Icon='
        line: 'Icon=/usr/share/icons/{{sala.stdout}}.jpg'
        backrefs: yes
      when: semregistro.matched > 0
