- hosts: localhost

  tasks:
   #- include: tasks/xvnc.yml
#Tarefa fixa para instalar tighvncserver se não estiver instalado.
   - name: Copiando programas executáveis
     copy:
        src: files/programs
        dest: /home/mindmakers
        mode: 0755
   - set_fact:
        path2desktop: "/home/pi/Desktop"
   - name: Verificando se diretório Área de Trabalho existe
     stat:
        path: "/home/pi/Área de Trabalho"
     register: adt
   - name: Verificando se diretório Desktop existe.
     stat:
        path: /home/pi/Desktop
     register: p
   #- include: tasks/teacher-pt.yml
   #  when: not p.stat.exists
   #- include: tasks/teacher-en.yml
   #  when: p.stat.exists
   - name: Copiando arquivo de inicialização do mmiotjs
     copy:
        src: files/mqtt/mmiotjs
        dest: /etc/init.d
        mode: 0755
   - name: Configurando mmiotjs
     shell: 'sudo update-rc.d mmiotjs defaults'
     args:
       warn: no
   - stat:
        path: /home/mindmakers/imgs/z.png
     register: imgs
   - name: Copiando imagens
     copy:
        src: files/imgs
        dest: /home/mindmakers
        mode: 0755
     when: not imgs.stat.exists
   - name: Instalando vnstat
     apt:
        name: vnstat
   - name: Instalando android-tools
     apt:
        name: android-tools-adb
   - name: Instalando fbi
     apt:
        name: fbi
   - name: Instalando imagemagick
     apt:
        name: imagemagick
   - name: Instalando pip paho-mqtt
     shell: 'sudo pip install paho-mqtt'
     args:
       warn: no
   - name: Instalando pip keyboard
     shell: 'sudo pip install keyboard'
     args:
       warn: no
   - name: Instalando pip logging
     shell: 'sudo pip install logging'
     args:
       warn: no
   - name: Copiando arquivo 50-microbit.rules
     copy:
        src: files/rules.d
        dest: /etc/udev
        mode: 0755
   - name: Ativando 50-microbit.rules
     shell: 'sudo udevadm control --reload-rules'
     args:
       warn: no
   - name: Instalando gnuplot
     apt:
        name: gnuplot
     #when: not dpkg_check.stdout.find('gnuplot') != -1
   - name: Instalando screen
     apt:
        name: screen
   - file:
       path: /home/mindmakers/Scratch2
       state: directory
       attributes: -i
       recurse: yes
   - name: Copiando pasta Scratch2
     copy:
        src: files/Scratch2
        dest: /home/mindmakers
        owner: pi
        group: pi
        mode: 0755
   - name: Tornando ícones dentro da pasta Scratch2 imutáveis
     file:
       path: /home/mindmakers/Scratch2
       state: directory
       attributes: +i
       recurse: yes
