- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
  - name: Ansible grep pattern basic example
    shell: "env | grep LANG"
    args:
      chdir: "/home/PI/Desktop"
    register: grep_output

  - debug:
      var: grep_output.stdout_lines
