- hosts: localhost
  become: true
  tasks:
  - name: Ansible grep pattern basic example
    shell: "env | grep LANG="
    register: shell_output
    vars: 
      - linguagem:  shell_output.stdout_lines
    
  - name: Troca imagem de fundo
    shell: "pcmanfm --set-wallpaper=*fundo_v1.png"
    args:
      chdir: "/home/pi/Desktop/"


  - debug:
      var: shell_output.stdout_lines
      msg={{ linguagem }}
     
