- hosts: localhost
  vars: 
    - ver: 6.9.0
  tasks:  
  - name: Verifica Versao npm
    shell: "npm --version"
    register: shell_output
    
  - debug:
      var: shell_output.stdout_lines
      assert:
        that:
          - shell_output.stdout_lines == ver
        register: n
    when: n.stat.exists
