- hosts: localhost

  tasks:
  - include: tasks/tightvnc.yml

#  - name: get the rpm package facts
#    package_facts:
#       manager: "auto"

#  - name: show them
#    debug: var=ansible_facts.packages


#  - name: Instalando pacote do npm "websocket" verificar se da skip se já estiver instalado
#  npm:
#    name: websocket
#    path: /home/mindmakers/programs
#    state: present

#tentativa adicionar || o final das linhas do arquivo school.info

  - name: Ver se máquina já foi ativada para fixar o ip do Rapsberry.
    find:
      paths: /home/mindmakers/
      patterns: 'school.info'
      contains: '||'
      use_regex: yes
    register: semregistro
    - debug:
       var: semregistro
  
  - lineinfile:
      path: /home/mindmakers/school.info
      regexp: 'Cód.: '
      insertafter: '||'
    when: semregistro.matched == 0
  - lineinfile:
      path: /home/mindmakers/school.info
      regexp: 'Nome: '
      insertafter: '||'
    when: semregistro.matched == 0
  - lineinfile:
      path: /home/mindmakers/school.info
      regexp: 'Pi: '
      insertafter: '||'
    when: semregistro.matched == 0
  - lineinfile:
      path: /home/mindmakers/school.info
      regexp: 'SD: '
      insertafter: '||'
    when: semregistro.matched == 0
  - lineinfile:
      path: /home/mindmakers/school.info
      regexp: 'Sphero: '
      insertafter: '||'
    when: semregistro.matched == 0
  - lineinfile:
      path: /home/mindmakers/school.info
      regexp: 'Sala: '
      insertafter: '||'
    when: semregistro.matched == 0
  - lineinfile:
      path: /home/mindmakers/school.info
      regexp: 'Estação: '
      insertafter: '||'
    when: semregistro.matched == 0
###############

######### verificar se o pacote ja foi instalado, tentar implementar para ambos apt e npm install.
#- name: Check if foo.rpm is installed
#  command: rpm -q foo.rpm
#  register: rpm_check

#- name: Execute script if foo.rpm is not installed
#  command: somescript
#  when: rpm_check.stdout.find('is not installed') != -1
#The rpm command will also exit with a 0 if the package exists, or a 1 if the package isn't found, so another possibility is to use:

#when: rpm_check.rc == 1

#Based on the Bruce P answer above, a similar approach for apt/deb files is

#- name: Check if foo is installed
#  command: dpkg-query -l foo
#  register: deb_check

#- name: Execute script if foo is not installed
#  command: somescript
#  when: deb_check.stdout.find('no packages found') != -1

######

  # Verifica se school.info ainda tem Pi não registrado para. true se não tiver e false se tiver.

#  - name: instalar ...
#    include: tasks/headless.yml

#pode ser utilzado para verificar se é Raspberry ou ChromeOS
#    - name: "testes"
#      command:
#      when: ansible_facts.lsb.id == "Raspbian"

#verificação de versão funcionando!!
#  - name: Verifica Versao npm
#    command: npm --version
#    register: shell_output
#  - debug:
#       var: apt_list
#    when: shell_output is version('6.0', '>=')

#precisa de ignorar o resultado para continuar rodando o playbook
#  - name: Ativa vnstat
#    command: lxterminal -e vnstat -l -i wlan0
#    changed_when: False
#    failed_when: False
#    when: ansible_facts.wlan0.active
#  - name: Ativa vnstat
#    command: lxterminal -e vnstat -l
#    when: ansible_facts.ansible_eth0.active


##########
# Verifica se school.info ainda tem Pi não registrado para. true se não tiver e false se tiver.
#  - name: Ver se máquina já foi ativada para fixar o ip do Rapsberry.
#    find:
#      paths: /home/mindmakers/       
#      patterns: 'school.info'
#      contains: 'Pi: Não'
#      use_regex: yes
#    register: semregistro2

  - debug:
       var: semregistro
#    when: semregistro.matched == 0
##########

#  - debug:
#       var: ansible_facts
#  - debug:
#       var: ansible_facts['os_family']
#  - debug:
#       var: ansible_facts.lsb
