- hosts: localhost
#  vars: 
#    - ver: 6.9.0
  tasks: 
#   - name: Testar raspi-config
#     include: tasks/raspi-config.yml
#  - name: instalar headless
#    include: tasks/headless.yml
  
  - name: Verifica Versao npm
    command: npm --version
    register: shell_output
#  - local_action: copy content="{{ ansible_facts }}" dest="/home/mindmakers/file"  
  - local_action: 
       copy content: "{{ansible_facts}}" 
       dest: "/home/mindmakers/file"
 
    
#  - debug:
#      var: shell_output
#      assert:
#        that:
#          - shell_output.stdout_lines == ver
#        register: n
#    when: n.stat.exists
 
  - debug:
       var: shell_output.stdout_lines
    when: shell_output is version('6.0', '<=')
    
  - debug: 
       var: ansible_facts
