- hosts: localhost
  become: true
  tasks:
  - name: Ansible grep pattern basic example
    shell: "grep -ir 'Pattern' *"
    args:
      chdir: "/home/PI/Desktop/"
    register: grep_output

  - debug:
      var: grep_output.stdout_lines
