- hosts: localhost

  tasks:
   #- include: tasks/xvnc.yml
#Tarefa fixa para instalar tighvncserver se não estiver instalado.

   - name: Instalando pip ansible
     shell: 'sudo pip install ansible'
     register: ansib
     args:
       warn: no


   - debug:
       var: ansib
   - name: fail the play if the previous command did not succeed
     fail:
       msg: "the command failed"
     when: ansb.stat.exists
   #- include: tasks/buster.yml
   #- include: tasks/avahi.yml

   # - name: Trocando imagem de fundo e posicionando ícones padrões do Desktop
   #   copy:
   #      src: files/pcmanfm/LXDE-pi/desktop-items-0.conf
   #      dest: /home/pi/.config/pcmanfm/LXDE-pi
   #      mode: 0755
   #- name: Personalizando barra superior
   #  copy:
   #     src: files/panel
   #     dest: /home/pi/.config/lxpanel/LXDE-pi/panels
   #     mode: 0755





#Funcionando mas precisa validar quais comandos realmente pode fazer sem o sudo.
#força pedir senha apra usar comando sudo para usuários pi.
#  - lineinfile:
#      path: /etc/sudoers.d/010_pi-nopasswd
#      regexp: '^pi ALL='
#      line: 'pi ALL=(ALL) ALL'
#      backrefs: yes
############


#  - debug:
#       var: ansible_facts
#  - debug:
#       var: ansible_facts['os_family']
#  - debug:
#       var: ansible_facts.lsb
