- hosts: localhost
  become: true
  vars: 
    - linguagem: teste
  tasks:
  - name: Ansible grep pattern basic example
    shell: "env | grep LANG="
    register: shell_output
    
  - name: Troca imagem de fundo
    command: "pcmanfm --set-wallpaper=/home/mindmakers/fundo.png"

  - debug:
      var: linguagem = {{shell_output.stdout_lines}}
