- hosts: localhost
  remote_user: root

  tasks:
   # - debug:
   #     var: ansible_facts.env
   # - name: Verificando se diretório Desktop existe.
   #   stat:
   #      path: "/home/pi/Desktop"
   #   register: desk
   # - debug:
   #     var: desk
   - set_fact:
        path2desktop: "/home/pi/Desktop"
     when: desk.stat.exists
   - name: Copiando arquivo usando caminho de variável
     copy:
        src: files/fundo-en.png
        dest: "{{ path2desktop }}"
        mode: 0755
   - name: Verificando se diretório Área de Trabalho existe.
     stat:
        path: "/home/pi/Área de Trabalho"
     register: adt
   - debug:
       var: adt
   - name: teste armazenar valor variavel 2
     set_fact:
        path2desktop: "{{ adt.stat.path }}"
     when: adt.stat.exists
   - debug:
       var: path2desktop
   - name: Copiando arquivo usando caminho de variável
     copy:
        src: files/fundo-en.png
        dest: "{{ path2desktop }}"
        mode: 0755


#   - name: Copiando arquivo usando caminho de variável 2
#     copy:
#        src: files/fundo-en.png
#        dest: {{ desk }}
#        mode: 0755
   - name: Verificando se diretório Desktop existe.
     stat:
        path: "/home/pi/Área de Trabalho"
     register: adt
   - debug:
       var: adt


   - debug:
       var: "'pt_BR' in ansible_facts.env.LANGUAGE"
   - debug:
       var: "'en_' in ansible_facts.env.LANGUAGE"
   - debug:
       msg: "Buster"
     when: ansible_facts.lsb.codename == "buster"
   - debug:
       msg: "not Buster"
     when: not ansible_facts.lsb.codename == "buster"
   - debug:
       msg: "Scretch"
     when: ansible_facts.lsb.codename == "scretch"
   - debug:
       msg: "not Scretch"
     when: not ansible_facts.lsb.codename == "scretch"
   # - name: Instalando pacote Ansible 2.7.*
   #   shell: 'apt-get install -y ansible'
   #   args:
   #      warn: no
   #   register: ansib
   # - debug:
   #     var: ansib

   #- include: tasks/xvnc.yml
#Tarefa fixa para instalar tighvncserver se não estiver instalado.

   # - name: Instalando pip ansible
   #   shell: 'sudo pip install ansible'
   #   register: ansib
   #   args:
   #     warn: no
   # - debug:
   #     var: ansib ansib.stdout
   # - name: Ansible foi atualizado
   #   fail:
   #     msg: "Reiniciar reiniciar ansible para continuar instalação"
   #   when: "not 'already satisfied' in ansib.stdout"
   #- include: tasks/buster.yml

   #- include: tasks/teacher-en.yml
  # - name: Validando ativação
  #   find:
  #      paths:  /etc/default/
  #      patterns: 'locale'
  #      contains: "^LANG="
  #      use_regex: yes
  #   register: language
  # - debug:
  #     var: language
# - file:
#     path: /home/pi/Desktop/scratch2_folder.desktop
#     state: touch
#     attributes: -i
   # - name:
   #   shell: 'sudo chattr -i /home/pi/Desktop/scratch2_folder.desktop'
   #   args:
   #     warn: no
   # - name: Alterando atalho da pasta Scratch2
   #   lineinfile:
   #     path: /home/pi/Desktop/scratch2_folder.desktop
   #     regexp: '^Exec=pcmanfm /home/mindmakers/Scratch2/portuguese'
   #     line: 'Exec=pcmanfm /home/mindmakers/Scratch2/english'
   #     backrefs: yes
   #   when: lang.stdout.find('LANG=en') != -1
   # - name:
   #   shell: 'sudo chattr +i /home/pi/Desktop/scratch2_folder.desktop'
   #   args:
   #     warn: no
   # - file:
   #     path: /home/pi/Scratch2
   #     state: absent
   # - shell: 'sudo ln -s /home/mindmakers/Scratch2/english /home/pi/Scratch2'
   #   args:
   #     warn: no
   #   when: lang.stdout.find('LANG=en') != -1
   # - shell: 'sudo ln -s /home/mindmakers/Scratch2/portuguese /home/pi/Scratch2'
   #   args:
   #     warn: no
   #   when: lang.stdout.find('LANG=pt') != -1
   # - file:
   #     path: /home/pi/Fotos
   #     state: absent
   # - file:
   #     path: /home/pi/Pictures/Pictures
   #     state: absent
   # - file:
   #     path: /home/pi/Pictures/Fotos
   #     state: absent
   # - shell: 'sudo ln -s /home/pi/Pictures /home/pi/Fotos'
   #   args:
   #     warn: no
   #   when: lang.stdout.find('LANG=pt') != -1


   # - name: Trocando imagem de fundo e posicionando ícones padrões do Desktop
   #   copy:
   #      src: files/pcmanfm/LXDE-pi/desktop-items-0.conf
   #      dest: /home/pi/.config/pcmanfm/LXDE-pi
   #      mode: 0755
   #- name: Personalizando barra superior
   #  copy:
   #     src: files/panel
   #     dest: /home/pi/.config/lxpanel/LXDE-pi/panels
   #     mode: 0755





#Funcionando mas precisa validar quais comandos realmente pode fazer sem o sudo.
#força pedir senha apra usar comando sudo para usuários pi.
#  - lineinfile:
#      path: /etc/sudoers.d/010_pi-nopasswd
#      regexp: '^pi ALL='
#      line: 'pi ALL=(ALL) ALL'
#      backrefs: yes
############


   # - debug:
   #     var: ansible_facts
   # - debug:
   #     var: ansible_facts['os_family']
   # - debug:
   #     var: ansible_facts.lsb
