- hosts: localhost

  tasks:
  - include: tasks/tightvnc.yml
#Tarefa fixa para instalar tighvncserver se não estiver instalado.

  - name: Verificando se NPM está instalado
    command: dpkg-query -l npm
    register: deb_check_npm
    ignore_errors: yes
    
  - debug:
       var: deb_check_npm
  
  - name: Instalando npm 1.4* se o pacote não estiver instalado
  apt:
     name: npm
  when: deb_check_npm.failed is true
  
  
#  - name: Escondendo Python-games
#    lineinfile:
#      path: /usr/share/applications/python-games.desktop
#      regexp: 'NoDisplay=true'
#      line: 'NoDisplay=true'
#      insertafter: EOF
#  - name: Escondendo Minecraft
#    lineinfile:
#      path: /usr/share/raspi-ui-overrides/applications/minecraft-pi.desktop
#      regexp: 'NoDisplay=true'
#      line: 'NoDisplay=true'
#      insertafter: EOF

#  - name: Verifica Versao npm
#    command: nodejs --version
#    register: node_output
#  - debug:
#       var: node_output
#  - name: Instalando Nodejs 8.15.1
#    apt:
#       name: nodejs
       #force_apt_get: yes
#    when: node_output.stdout is version('8.12.0', '<')


#Funcionando mas precisa validar quais comandos realmente pode fazer sem o sudo.
#força pedir senha apra usar comando sudo para usuários pi.
#  - lineinfile:
#      path: /etc/sudoers.d/010_pi-nopasswd
#      regexp: '^pi ALL='
#      line: 'pi ALL=(ALL) ALL'
#      backrefs: yes
############

#############
#  - name: Verifica Versao tightvnc
#    command: Xvnc -version
#    ignore_errors: yes
#    register: vnc_output
#  - debug:
#      var: vnc_output
#  - include: tasks/tightvnc.yml
#    when: not vnc_output.stderr is search("Xvnc version TightVNC-*")
############


#Funciona para verificar versão de pacotes instalados

#  - name: Check if foo is installed
#    command: dpkg-query -l tightvncserver
#    register: deb_check
#  - debug:
#       var: deb_check
#  - include: tasks/tightvnc.yml
#    when: deb_check.stdout.find('<nenhuma>') != -1

######

  # Verifica se school.info ainda tem Pi não registrado para. true se não tiver e false se tiver.

#  - name: instalar ...
#    include: tasks/headless.yml


#verificação de versão funcionando!!
#  - name: Check if npm is installed
#    command: dpkg-query -l npm
#    register: deb_check_npm
#  - debug:
#       var: deb_check_npm
#  - debug:
#       mgs: fez o treco
#    when: deb_check_npm.stdout.find('<nenhuma>') != -1
#  - name: Verifica Versao npm
#    command: 'npm ls --depth 0'
#    args:
#       chdir: /home/mindmakers/programs/
#    register: npm_dep_output
#    ignore_errors: yes
#  - debug:
#       var: npm_dep_output

 # - name: Instalando Nodejs 8.15.3
 #   apt:
 #     name: nodejs
 #   force_apt_get: yes
 #   when: npm_output.stdout is version('8.15.0', '<')

#  - name: Atualiza o npm se versão < 6.9
#    npm: name={{item}} global=yes
#    with_items:
#      - npm
#      - npm
#    when: npm_output is version('6.0', '>=')

#  - name: Verifica Versao npm
#    command: nodejs --version
#    register: shell_output
#  - debug:
#       var: shell_output
#  - debug:
#       msg: versao superior precisa ser instalada
#    when: shell_output.stdout is version('8.13*', '<=')

#precisa de ignorar o resultado para continuar rodando o playbook
#  - name: Ativa vnstat
#    command: lxterminal -e vnstat -l -i wlan0
#    changed_when: False
#    failed_when: False
#    when: ansible_facts.wlan0.active
#  - name: Ativa vnstat
#    command: lxterminal -e vnstat -l
#    when: ansible_facts.ansible_eth0.active
  # - file:
   #    path: /home/pi/.config/pcmanfm/LXDE-pi/desktop-items-0.conf
  #     state: touch
 #      attributes: -i
 #  - name: Trocando imagem de fundo e posicionando ícones padrões do Desktop
 #    copy:
#        src: files/pcmanfm/LXDE-pi/desktop-items-0.conf
#        dest: /home/pi/.config/pcmanfm/LXDE-pi
#        mode: 0755
#   - name: Verificando OS em inglês
#     shell: 'cat /etc/default/locale | grep LANG= '
#     register: lang
#   - name: Alterando fundo.png para fundo-en.png
#     lineinfile:
#       path: /home/pi/.config/pcmanfm/LXDE-pi/desktop-items-0.conf
#       regexp: '^wallpaper=/home/mindmakers/fundo.png'
#       line: 'wallpaper=/home/mindmakers/fundo-en.png'
#       backrefs: yes
#     when: lang.stdout.find('LANG=en') != -1
#   - file:
#       path: /home/pi/.config/pcmanfm/LXDE-pi/desktop-items-0.conf
#       state: touch
#       attributes: +i


##########
# Verifica se school.info ainda tem Pi não registrado para. true se não tiver e false se tiver.
#  - name: Ver se máquina já foi ativada para fixar o ip do Rapsberry.
#    find:
#      paths: /home/mindmakers/
#      patterns: 'school.info'
#      contains: 'Pi: Não'
#      use_regex: yes
#    register: semregistro2
#  - name: Ver se máquina já foi ativada para fixar o ip do Rapsberry.
#    find:
#      paths: /home/mindmakers/
#      patterns: 'school.info'
#      contains: 'Pi: Não'
#      use_regex: yes
#    register: semregistro2

#  - debug:
#       var: semregistro2
#    when: semregistro.matched == 0
##########

#  - debug:
#       var: ansible_facts
#  - debug:
#       var: ansible_facts['os_family']
#  - debug:
#       var: ansible_facts.lsb
