- hosts: localhost

  tasks:
  # Verifica se school.info ainda tem Pi não registrado para. true se não tiver e false se tiver.
  - name: Ver se máquina já foi ativada para fixar o ip do Rapsberry.
    find:
       paths: /home/mindmakers/
       patterns: 'school.info'
       contains: 'Pi: Não'
       use_regex: yes
    register: semregistro
    
  - debug:
       var: semregistro
    
  - name: Executando version_update.js
    command: nodejs mmversionupdate.js
    args:
      chdir: /home/mindmakers/programs
    when: not semregistro.stat.exists

  
#  - meta: end_play
#    when: not ansible_facts.lsb.id == "Raspbian"
    
#  - fail:
#       msg: "Você não está tentando cessar o playbook errado."
#    when: ansible_facts.lsb.id == "Raspbian"
#  - name: instalar headless
#    include: tasks/headless.yml

#pode ser utilzado para verificar se é Raspberry ou ChromeOS
#    - name: "testes"
#      command:
#      when: ansible_facts.lsb.id == "Raspbian"

#verificação de versão funcionando!!
#  - name: Verifica Versao npm
#    command: npm --version
#    register: shell_output
#  - debug:
#       var: apt_list
#    when: shell_output is version('6.0', '>=')

#precisa de ignorar o resultado para continuar rodando o playbook
#  - name: Ativa vnstat
#    command: lxterminal -e vnstat -l -i wlan0
#    changed_when: False
#    failed_when: False
#    when: ansible_facts.wlan0.active
#  - name: Ativa vnstat
#    command: lxterminal -e vnstat -l
#    when: ansible_facts.ansible_eth0.active


##########
# Verifica se school.info ainda tem Pi não registrado para. true se não tiver e false se tiver.
#  - name: Ver se máquina já foi ativada para fixar o ip do Rapsberry.
#    find:
#      paths: /home/mindmakers/
#      patterns: 'school.info'
#      contains: 'Pi: Não'
#      use_regex: yes
#    register: semregistro
#
#  - debug:
#       var: semregistro
##########



###########################
#  - debug:
#       var: ansible_facts.wlan0.ipv4.address
#    when: ansible_facts.wlan0.active

#   - name: Testar version update
#     include: version_update.yml


  - debug:
       var: ansible_facts
#  - debug:
#       var: ansible_facts['os_family']
#  - debug:
#       var: ansible_facts.lsb
