- hosts:       all
  remote_user: root
  
  tasks:

    # - include:         tasks/rpimonitor.yml
    #
    # - include:         tasks/ansibleVirtualENV.yml
    # - include:         tasks/reboot.yml
    #
- name:     update chromium para release 88.
  apt:
    name:   chromium-browser=88.0.4324.187
    state:  fixed

    # - include:         tasks/student-en.yml

    #
    # - file:
    #     path:          /home/pi/sketchbook
    #     state:         absent
    # - name:            copiando arquivos sketchbook
    #   copy:
    #      src:          files/arduino/sketchbook
    #      dest:         /home/pi/
    #      owner:        pi
    #      group:        pi
    #      mode:         0755
    # - name:            Criando pastas de sketchbook
    #   file:
    #     path:          /home/pi/.arduino
    #     state:         directory
    #     mode:          0755
    # - name:            copiando arquivos sketchbook
    #   copy:
    #      src:          files/arduino/preferences.txt
    #      dest:         /home/pi/.arduino
    #      owner:        pi
    #      group:        pi
    #      mode:         0755
    # - name:            Criando pastas de sketchbook
    #   file:
    #     path:          /home/pi/sketchbook
    #     state:         directory
    #     mode:          0755
    # - name:            Criando pastas de libraries
    #   file:
    #     path:          /home/pi/sketchbook/libraries
    #     state:         directory
    #     mode:          0755
    # - name:            Criando pastas de FirmataExpress
    #   file:
    #     path:          /home/pi/sketchbook/libraries/FirmataExpress
    #     state:         directory
    #     mode:          0755
    # - name:            copiando arquivos sketchbook
    #   copy:
    #      src:          ongoing/arduino/sketchbook/libraries/FirmataExpress
    #      dest:         /home/pi/sketchbook/libraries
    #      owner:        pi
    #      group:        pi
    #      mode:         0755

    # - stat:
    #      path:         /home/mindmakers/imgs/win.png
    #   register:        imgs
    # - file:
    #     path:          /home/mindmakers/vw
    #     state:         absent
    # - file:
    #     path:          /home/mindmakers/mmiotcli.js
    #     state:         absent
    #
    # - name:            Copiando arquivos de imagens
    #   copy:
    #      src:          files/icons
    #      dest:         /usr/share
    #      mode:         0777
    # - name:            Trocando imagem de fundo e posicionando ícones padrões do Desktop
    #   copy:
    #      src:          files/pcmanfm/LXDE-pi/desktop-items-0.conf
    #      dest:         /home/pi/.config/pcmanfm/LXDE-pi
    #      mode:         0755


    # - name:            Copiando programs
    #   copy:
    #      src:          files/programs
    #      dest:         /home/mindmakers
    #      mode:         0755


    # - name:            Copiando vw
    #   copy:
    #      src:          files/programs/vw
    #      dest:         /home/mindmakers/programs
    #      mode:         0755
    # - name:            Copiando cli
    #   copy:
    #      src:          files/programs/mmiotcli.js
    #      dest:         /home/mindmakers/programs
    #      mode:         0755


    #
    #
    # - name:            Instalando pacote do npm "cors"
    #   npm:
    #     name:          cors
    #     # version:     '4.1.1'
    #     path:          /home/mindmakers/programs
    # #   when:          not imgs.stat.exists
    # - include:         tasks/reboot.yml
    #
    # - set_fact:
    #      path2desktop: "/home/pi/Desktop"
    # - name:            Verificando se diretório Área de Trabalho existe
    #   stat:
    #      path:         "/home/pi/Área de Trabalho"
    #   register:        adt
    # - set_fact:
    #      path2desktop: "{{ adt.stat.path }}"
    #   when:            adt.stat.exists
    # - name:            Alterando atributos do atalho da pasta scratch2
    #   shell:           'sudo chattr -i /home/pi/Desktop/classroom_test.desktop'
    #   args:
    #     warn:          no
    # - copy:
    #      src:          files/classroom_test.desktop
    #      dest:         "{{ path2desktop }}/classroom_test.desktop"
    #      owner:        pi
    #      group:        pi
    #      mode:         0755
    # - lineinfile:
    #     path:          "{{ path2desktop }}/classroom_test.desktop"
    #     regexp:        '^Icon='
    #     line:          'Icon=/usr/share/icons/{{sala.stdout}}.jpg'
    #     backrefs:      yes
    # - name:            Alterando atributos do atalho da pasta scratch2
    #   shell:           'sudo chattr +i /home/pi/Desktop/classroom_test.desktop'
    #   args:
    #     warn:          no

    #arquivo original
    # - name:            Copiando arquivo de inicialização do mmiotjs
    #   copy:
    #      src:          files/autostart/mmiotjs
    #      dest:         /etc/init.d
    #      mode:         0755
    # - shell:           'sudo update-rc.d mmiotjs defaults'
    #   args:
    #     warn:          no

    # - name:     Copiando arquivo de inicialização do s3r
    #   copy:
    #      src:   ongoing/autostart-tst/mmiotjs/mmiotjs
    #      dest:  /etc/init.d
    #      mode:  0755
    # - name:     Configurando reinicio automático do serviço mmgpio
    #   copy:
    #      src:   ongoing/autostart-tst/mmiotjs/mmiotjs.service.d
    #      dest:  /etc/systemd/system
    #      mode:  0755
    # - shell:    'sudo update-rc.d mmiotjs defaults'
    #   args:
    #     warn:   no
    # - shell:    'sudo systemctl daemon-reload'
    #   args:
    #     warn:   no



    # - include:         tasks/reboot.yml
