- hosts: localhost

  tasks:
####Funcionando mas precisa ver se vai usar  
#  - file:
#       path: /home/mindmakers/programs/mmtelebot.py
#       state: touch
#       mode: 0711
#tornar arquivo mmtelebot somente execultavem para níveis grupo e owner

#Funcionando mas precisa validar quais comandos realmente pode fazer sem o sudo.
#força pedir senha apra usar comando sudo para usuários pi.       
#  - lineinfile:
#      path: /etc/sudoers.d/010_pi-nopasswd
#      regexp: '^pi ALL='
#      line: 'pi ALL=(ALL) ALL'
#      backrefs: yes
############

#############   
#  - name: Verifica Versao tightvnc
#    command: Xvnc -version
#    ignore_errors: yes
#    register: vnc_output
#  - debug:
#      var: vnc_output
#  - include: tasks/tightvnc.yml
#    when: not vnc_output.stderr is search("Xvnc version TightVNC-*")
############

#  - name: get the rpm package facts
#    package_facts:
#       manager: "auto"

#  - name: show them
#    debug: var=ansible_facts.packages


#  - name: Instalando pacote do npm "websocket" verificar se da skip se já estiver instalado
#    npm:
#      name: websocket
#      path: /home/mindmakers/programs
#      state: present

#tentativa adicionar || o final das linhas do arquivo school.info





#Based on the Bruce P answer above, a similar approach for apt/deb files is

  - name: Check if foo is installed
    command: dpkg-query -l tightvncserver
    register: deb_check
  - debug:
       var: deb_check
  - name: Execute script if foo is not installed
    command: apt-get install tightvncserver
    when: deb_check.stdout.find('tightvncserve <') != -1

######

  # Verifica se school.info ainda tem Pi não registrado para. true se não tiver e false se tiver.

#  - name: instalar ...
#    include: tasks/headless.yml

#pode ser utilzado para verificar se é Raspberry ou ChromeOS
#    - name: "testes"
#      command:
#      when: ansible_facts.lsb.id == "Raspbian"

#verificação de versão funcionando!!
#  - name: Verifica Versao npm
#    command: npm --version
#    register: shell_output
#  - debug:
#       var: apt_list
#    when: shell_output is version('6.0', '>=')

#  - name: Verifica Versao npm
#    command: nodejs --version
#    register: shell_output
#  - debug:
#       var: shell_output
#  - debug:
#       msg: versao superior precisa ser instalada
#    when: shell_output.stdout is version('8.13*', '<=')

#precisa de ignorar o resultado para continuar rodando o playbook
#  - name: Ativa vnstat
#    command: lxterminal -e vnstat -l -i wlan0
#    changed_when: False
#    failed_when: False
#    when: ansible_facts.wlan0.active
#  - name: Ativa vnstat
#    command: lxterminal -e vnstat -l
#    when: ansible_facts.ansible_eth0.active


##########
# Verifica se school.info ainda tem Pi não registrado para. true se não tiver e false se tiver.
#  - name: Ver se máquina já foi ativada para fixar o ip do Rapsberry.
#    find:
#      paths: /home/mindmakers/
#      patterns: 'school.info'
#      contains: 'Pi: Não'
#      use_regex: yes
#    register: semregistro2- name: Ver se máquina já foi ativada para fixar o ip do Rapsberry.
#    find:
#      paths: /home/mindmakers/
#      patterns: 'school.info'
#      contains: 'Pi: Não'
#      use_regex: yes
#    register: semregistro2

#  - debug:
#       var: semregistro2
#    when: semregistro.matched == 0
##########

#  - debug:
#       var: ansible_facts
#  - debug:
#       var: ansible_facts['os_family']
#  - debug:
#       var: ansible_facts.lsb
