- hosts: localhost
  vars: 
    - linguagem: teste
  tasks:  
  - name: Verifica Linguagem OS
    shell: "npm --version"
    register: shell_output
    
  - debug:
      var: shell_output.stdout_lines  
