- hosts: localhost
  remote_user: root

  tasks:
 - include: tasks/xvnc.yml
   - set_fact:
        path2desktop: "/home/pi/Desktop"
   - name: Verificando se diretório Área de Trabalho existe
     stat:
        path: "/home/pi/Área de Trabalho"
     register: adt
   - set_fact:
        path2desktop: "{{ adt.stat.path }}"
     when: adt.stat.exists
   - name:
     shell: 'sudo chattr -i /home/pi/Desktop/scratch2_folder.desktop'
     args:
       warn: no

   - debug:
       var: "'pt_BR' in ansible_facts.env.LANGUAGE"
   - debug:
       var: "'en_' in ansible_facts.env.LANGUAGE"
   - debug:
       msg: "Buster"
     when: ansible_facts.lsb.codename == "buster"
   - debug:
       msg: "not Buster"
     when: not ansible_facts.lsb.codename == "buster"
   - debug:
       msg: "Scretch"
     when: ansible_facts.lsb.codename == "scretch"
   - debug:
       msg: "not Scretch"
     when: not ansible_facts.lsb.codename == "scretch"


   # - debug:
   #     var: ansible_facts
   # - debug:
   #     var: ansible_facts['os_family']
   # - debug:
   #     var: ansible_facts.lsb
