- hosts: localhost
  become: true
  tasks:
  - name: Ansible grep pattern basic example
    shell: "env | grep LANG="
    register: shell_output = pt
    when: ansible_facts['shell_output.stdout_lines'] == "LANG=pt_BR"

  - debug:
      var: shell_output
