- hosts: localhost
  become: true
  tasks:
  - name: Ansible grep pattern basic example
    shell: "env | grep LANG="
    register: shell_output

  - debug:
      when: ansible_facts['shell_output.stdout_lines'] == "LANG=pt_BR"
           var: shell_output.stdout_lines
