- hosts: localhost
  vars: 
    - ver: 6.9.0
  tasks:  
  - name: Verifica Versao npm
    shell: "npm --version"
    register: shell_output
    
  - name: Assertando
    assert:
      that:
        - "shell_output.stdout_lines >= 6.9.0"
 #     register: n
      fail_msg: "'shell_output.stdout_lines' must be between 0 and 100"
      success_msg: "'shell_output.stdout_lines' is between 0 and 100"
    
  - debug:
      var: shell_output.stdout_lines
#      assert:
#        that:
#          - shell_output.stdout_lines == ver
#        register: n
    when: n.stat.exists
 
#  - debug:
#      var: shell_output.stdout_lines
#    when: assert= { that= "shell_output.stdout_lines == '6.9.0'" }
    
#- name: after version 2.7 both 'msg' and 'fail_msg' can customize failing assertion message
#  assert:
#    that:
#      - "my_param <= 100"
#      - "my_param >= 0"
#   
#    success_msg: "'my_param' is between 0 and 100"
