- hosts: localhost
  become: true
  tasks:
  - name: Ansible grep pattern basic example
    shell: "env | grep LANG="
    register: shell_output
    linguagem: shell_output.stdout_lines
    debug: msg={{ linguagem }}
    
  - name: Troca imagem de fundo
    shell: "pcmanfm --set-wallpaper=*fundo_v1.png"
    args:
      chdir: "/home/pi/Desktop/"


  - debug:
      var: linguagem
