- hosts: localhost
  become: true
  tasks:
  - name: Ansible grep pattern basic example
    shell: "env | grep LANG="
    register: shell_output
    
  - name: Troca imagem de fundo
    shell: "pcmanfm --set-wallpaper=*.png"
    args:
      chdir: "/home/mindmakers/"


  - debug:
      var: shell_output.stdout_lines
