- name: Instala libgles2-mesa e libsdl2-dev
  apt: name={{item}}
  with_items:
    - libgles2-mesa
    - libsdl2-dev
    
- name: Cria links simbolicos necessarios do 3DSlash
  shell: "{{ item }}"
  with_items:
    - 'cd /opt/vc/lib'  
    - 'ln -s /opt/vc/liblibbrcmEGL.so /opt/vc/liblibEGL.so'
    - 'ln -s /opt/vc/liblibbrcmGLESv2.so /opt/vc/liblibGLESv2.so'
    - 'ln -s /opt/vc/liblibbrcmOpenVG.so /opt/vc/liblibOpenVG.so'
    - 'ln -s /opt/vc/liblibbrcmWFC.so /opt/vc/liblibWFC.so'
    - 'ln -fs /opt/vc/lib/libEGL.so /usr/lib/arm-linux-gnueabihf/libEGL.so'
    - 'ln -fs /opt/vc/lib/libGLESv2.so /usr/lib/arm-linux-gnueabihf/libGLESv2.so'
    - 'ldconfig'

#  shell: 'cd /opt/vc/lib && ln -s libbrcmEGL.so libEGL.so'
#  shell: 'cd /opt/vc/lib && ln -s libbrcmGLESv2.so libGLESv2.so'
#  shell: 'cd /opt/vc/lib && ln -s libbrcmOpenVG.so libOpenVG.so'
#  shell: 'cd /opt/vc/lib && ln -s libbrcmWFC.so libWFC.so'
#  shell: 'ln -fs /opt/vc/lib/libEGL.so /usr/lib/arm-linux-gnueabihf/libEGL.so'
#  shell: 'ln -fs /opt/vc/lib/libGLESv2.so /usr/lib/arm-linux-gnueabihf/libGLESv2.so'
#  shell: 'ldconfig'

#sudo raspi-config
#
#choose Advanced Options | Memory Split, enter 256,
# then Tab to OK and press Enter.
#
#cd Downloads
#sudo tar -xvzpf 3dslash_raspberry_3_0_0.tgz -C /usr/local
#sudo chown -R root:staff /usr/local/3DSlash
#sudo apt-get install -y libgles2-mesa libsdl2-dev
#
#cd /opt/vc/lib
#sudo ln -s libbrcmEGL.so libEGL.so
#sudo ln -s libbrcmGLESv2.so libGLESv2.so
#sudo ln -s libbrcmOpenVG.so libOpenVG.so
#sudo ln -s libbrcmWFC.so libWFC.so
#sudo ln -fs /opt/vc/lib/libEGL.so /usr/lib/arm-linux-gnueabihf/libEGL.so
#sudo ln -fs /opt/vc/lib/libGLESv2.so /usr/lib/arm-linux-gnueabihf/libGLESv2.so
#sudo ldconfig
#
#/usr/local/3DSlash/3DSlash-pi
