- name: Verifica se 3DSlash já existe
  stat:
     path: /home/mindmakers/programs/verify/3DSlash
  register: slash
- name: Copia arquivos 3DSlash
  copy: src=ongoing/3DSlash dest=/home/mindmakers/programs/verify/ mode=644
  when: not slash.stat.exists
- name: Extrai 3DSlash
  shell: 'cd /home/mindmakers/programs/verify/3DSlash/ && tar -xvzpf 3dslash_raspberry_3_0_0.tgz -C /usr/local'
  when: not slash.stat.exists
- name: Instala 3DSlash
  shell: 'cd /home/mindmakers/programs/verify/3DSlash/ && chown -R root:staff /usr/local/3DSlash'
  when: not slash.stat.exists
  
- name: Instala libgles2-mesa e libsdl2-dev
  apt: name={{item}}
  with_items:
    - libgles2-mesa
    - libsdl2-dev
    
- name: Cria links simbolicos necessarios do 3DSlash
  shell: "{{ item }}"
  with_items: 
    - 'sudo ln -s /opt/vc/lib/libbrcmEGL.so /opt/vc/lib/libEGL.so'
    - 'sudo ln -s /opt/vc/lib/libbrcmGLESv2.so /opt/vc/lib/libGLESv2.so'
    - 'sudo ln -s /opt/vc/lib/libbrcmOpenVG.so /opt/vc/lib/libOpenVG.so'
    - 'sudo ln -s /opt/vc/lib/libbrcmWFC.so /opt/vc/lib/libWFC.so'
    - 'sudo ln -fs /opt/vc/lib/libEGL.so /usr/lib/arm-linux-gnueabihf/libEGL.so'
    - 'sudo ln -fs /opt/vc/lib/libGLESv2.so /usr/lib/arm-linux-gnueabihf/libGLESv2.so'
    - 'sudo ldconfig'

  
#sudo raspi-config
#
#choose Advanced Options | Memory Split, enter 256,
# then Tab to OK and press Enter.
#
#cd Downloads
#sudo tar -xvzpf 3dslash_raspberry_3_0_0.tgz -C /usr/local
#sudo chown -R root:staff /usr/local/3DSlash
#sudo apt-get install -y libgles2-mesa libsdl2-dev
#
#cd /opt/vc/lib
#sudo ln -s libbrcmEGL.so libEGL.so
#sudo ln -s libbrcmGLESv2.so libGLESv2.so
#sudo ln -s libbrcmOpenVG.so libOpenVG.so
#sudo ln -s libbrcmWFC.so libWFC.so
#sudo ln -fs /opt/vc/lib/libEGL.so /usr/lib/arm-linux-gnueabihf/libEGL.so
#sudo ln -fs /opt/vc/lib/libGLESv2.so /usr/lib/arm-linux-gnueabihf/libGLESv2.so
#sudo ldconfig
#
#/usr/local/3DSlash/3DSlash-pi
