- name: Adicionando pacote Ansible 2.7
  shell: 'echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list'
- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 93C4A3FD7BB9C367
- name: Atualizando repositórios
  apt:
    update_cache: yes
- name: Criando pastas de verificação
  file:
    path: /home/mindmakers
    state: directory
    mode: 0755
- file:
    path: /home/mindmakers/programs
    state: directory
    mode: 0755
- file:
    path: /home/mindmakers/programs/verify
    state: directory
    mode: 0755
- file:
    path: /home/mindmakers/programs/verify/ansible27
    state: directory
    mode: 0444
- name: Instalando pacote ansible 2.7
  shell: 'apt-get install -y ansible'
