- name: Copia sources.list
  copy:
     src: files/headless/sources.list
     dest: /etc/apt
     mode: 0644
- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 93C4A3FD7BB9C367
- name: Update repositories cache
  apt:
    update_cache: yes
#- name: Cria pasta de verificação instalação ansible 2.7
#  copy:
#     src: ongoing/verify/ansible27
#     dest: /home/mindmakers/programs/verify
#     mode: 0444
- name: Cria pasta de verificação
  file:
    path: /home/mindmakers/programs/verify/
    state: directory
    mode: 0444
- file:
    path: /home/mindmakers/programs/verify/ansible27
    state: directory
    mode: 0444
- name: Instala pacote ansible 2.7
  shell: 'apt-get install -y ansible'
