# - name: Adicionando pacote Ansible 2.7
#   shell: 'echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list'
#mais elegante e nao adiciona duplicado
#- name: Adicionando pacote Ansible
#  lineinfile:
#      path: /etc/apt/sources.list
#      regexp: 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main'
#      line: 'deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main'
#      insertafter: EOF
#- name: configura instalação do pacote ansible 2.7
#  shell: 'apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367'
#  args:
#     warn: no
# - name: Configurando instalação do pacote ansible 2.7
#   apt_key:
#     keyserver: keyserver.ubuntu.com
#     id: 93C4A3FD7BB9C367
- name: Atualizando Repositórios
  apt:
    update_cache: yes
- name: Criando pastas de verificação
  file:
    path: /home/mindmakers
    state: directory
    mode: 0755
- file:
    path: /home/mindmakers/programs
    state: directory
    mode: 0755
- file:
    path: /home/mindmakers/programs/verify
    state: directory
    mode: 0755
- file:
    path: /home/mindmakers/programs/verify/ansible27
    state: directory
    mode: 0444
# - name: Fazendo upgrade do Ansible
#   apt:
#      name: ansible
#   register: ansib
#- name: Instalando pacote Ansible 2.7.*
#  shell: 'apt-get install -y ansible'
#  args:
#     warn: no
#  register: ansib
#- name: instalação ansible 2.7 via pip
#  pip:
#     name: ansible~=2.7.0
- name: Instalando pip ansible
  shell: 'sudo pip install -U ansible'
  register: ansib
  args:
    warn: no
# - debug:
#     var: ansib
- name: Ansible foi atualizado
  fail:
    msg: "Reinicie a instalação via ansible para continuar a configuração da estação"
  when: "'installed' in ansib.stdout"
#- name: Instalando pip ansible
#  shell: 'sudo pip install ansible~=2.7.0'
#  args:
#    warn: no
