- name: Update all packages to the latest version
  apt:
    upgrade: dist
    
# - name: Update FULL all packages to the latest version
#   apt:
#     upgrade: full

- name: Removendo pacotes desnecessários do cache
  apt:
    autoclean: yes

- name: Removendo dependências que não são mais necessárias
  apt:
    autoremove: yes
