#- name: Update all packages to the latest version
#  apt:
#    upgrade: dist

- name: Removendo pacotes desnecessários da cache
  apt:
    autoclean: yes

- name: Removendo dependencas que não são mais necessárias
  apt:
    autoremove: yes
