# - name: Atualizando a distribuição do sistema.
#   apt:
#     upgrade: dist

- name: Removendo pacotes desnecessários do cache
  apt:
    autoclean: yes

- name: Removendo dependências que não são mais necessárias
  apt:
    autoremove: yes
