- name: Verificando numero da sala
  shell: "sudo grep -w 'Sala:' /home/mindmakers/school.info | sed 's/.*: //' | sed 's/||//'"
  register: sala
- name: Verificando numero da sala
  shell: "sudo grep -w 'Estação:' /home/mindmakers/school.info | sed 's/.*: //' | sed 's/||//'"
  register: estacao
- name: Validando ativação
  find:
     paths: /home/mindmakers/
     patterns: 'school.info'
     contains: "^Sala: [0-9]+"
     use_regex: yes
  register: semregistro
- name: Alterando nome do host avahi
  lineinfile:
    path: /etc/avahi/avahi-daemon.conf
    regexp: '^#host-name='
    line: 'host-name=raspberry-s{{sala.stdout}}e{{estacao.stdout}}'
    backrefs: yes
  #when: semregistro.matched > 0
- name: Alterando nome do host avahi
  lineinfile:
    path: /etc/avahi/hosts
    regexp: '^localhost:'
    line: 'localhost:3000 raspberry-s{{sala.stdout}}e{{estacao.stdout}}.local'
    insertafter: EOF
  #when: semregistro.matched > 0
#- debug:
#     var: sala
#- debug:
#     var: estacao
#- debug:
#     msg: "s{{sala.stdout}}e{{estacao.stdout}}"
##################
# - lineinfile:
#     path: /etc/avahi/avahi-daemon.conf
#     regexp: '^#publish-addresses=yes'
#     line: 'publish-addresses=yes'
#     backrefs: yes
# - lineinfile:
#     path: /etc/avahi/avahi-daemon.conf
#     regexp: '^#publish-domain=yes'
#     line: 'publish-domain=yes'
#     backrefs: yes
# - lineinfile:
#     path: /etc/avahi/avahi-daemon.conf
#     regexp: '^publish-hinfo=no'
#     line: 'publish-hinfo=yes'
#     backrefs: yes
# - lineinfile:
#     path: /etc/avahi/avahi-daemon.conf
#     regexp: '^publish-workstation=no'
#     line: 'publish-workstation=yes'
#     backrefs: yes
#
