- name: Validando ativação
  find:
     paths: /home/mindmakers/
     patterns: 'school.info'
     contains: "^Sala: [0-9]+"
     use_regex: yes
  register: semregistro
- name: Verificando numero da sala
  shell: "sudo grep -w 'Sala:' /home/mindmakers/school.info | sed 's/.*: //' | sed 's/||//'"
  args:
    warn: no
  register: sala
  when: semregistro.matched > 0
- name: Verificando numero da sala
  shell: "sudo grep -w 'Estação:' /home/mindmakers/school.info | sed 's/.*: //' | sed 's/||//'"
  args:
    warn: no
  register: estacao
  when: semregistro.matched > 0
# só alterar se a linha estiver comentada
# - name: Alterando nome do host avahi
#   lineinfile:
#     path: /etc/avahi/avahi-daemon.conf
#     regexp: '^host-name='
#     line: 'host-name=s{{sala.stdout}}e{{estacao.stdout}}'
#     backrefs: yes
#   when: semregistro.matched > 0
- name: Alterando nome do host avahi <9
  lineinfile:
    path: /etc/avahi/avahi-daemon.conf
    regexp: '^#host-name='
    line: 'host-name=s{{sala.stdout}}e0{{estacao.stdout}}'
    backrefs: yes
  when: semregistro.matched > 0 and estacao.stdout <= "9"
# - lineinfile:
#     path: /etc/avahi/avahi-daemon.conf
#     regexp: '^host-name='
#     line: 'host-name=s{{sala.stdout}}e0{{estacao.stdout}}'
#     backrefs: yes
#   when: semregistro.matched > 0 and estacao.stdout <= "9"
- name: Alterando nome do host avahi>=10
  lineinfile:
    path: /etc/avahi/avahi-daemon.conf
    regexp: '^#host-name='
    line: 'host-name=s{{sala.stdout}}e{{estacao.stdout}}'
    backrefs: yes
  when: semregistro.matched > 0 and estacao.stdout >= "10"
# - lineinfile:
#     path: /etc/avahi/avahi-daemon.conf
#     regexp: '^host-name='
#     line: 'host-name=s{{sala.stdout}}e{{estacao.stdout}}'
#     backrefs: yes
#   when: semregistro.matched > 0 and estacao.stdout >= "10"
# - name: Alterando nome do host avahi
#   lineinfile:
#     path: /etc/avahi/hosts
#     regexp: '^localhost:'
#     line: 'localhost:3000 s{{sala.stdout}}e{{estacao.stdout}}.local'
#     insertafter: EOF
#   when: semregistro.matched > 0
#- debug:
#     var: sala
#- debug:
#     var: estacao
#- debug:
#    msg: "s{{sala.stdout}}e0{{estacao.stdout}}"
