- name: Verificando numero da sala
  shell: 'sudo grep -w "Sala:" /home/mindmakers/school.info | sed 's/.*: //' | sed 's/||//''
  register: sala
- debug:
     var: sala
- name: Verificando numero da sala
  shell: 'sudo grep -w "Estação:" /home/mindmakers/school.info | sed 's/.*: //' | sed 's/||//''
  register: estacao
- debug:
     var: estacao
- debug:
     msg: "s{{sala.stdout}}e{{estacao.stdout}}"
# - name: Alterando nome do host avahi
#   lineinfile:
#     path: /etc/avahi/avahi-daemon.conf
#     regexp: '^#host-name='
#     line: 'host-name=raspberry-s{{sala.stdout}}e{{estacao.stdout}}'
#     backrefs: yes
# - name: Alterando nome do host avahi
#   lineinfile:
#     path: /etc/avahi/hosts
#     regexp: '^localhost:'
#     line: 'localhost:3000 raspberry-s{{sala.stdout}}e{{estacao.stdout}}'
#     insertafter: EOF
