- name: Copia arquivos de imagens
  copy: src=files/icons dest=/usr/share owner=root group=root mode=0440
- name: Copia arquivos de atalhos
  copy: src=files/Desktop/ dest=/home/pi owner=root group=root mode=0440
- name: Copiar programas
  copy: src=files/programs dest=/home/mindmakers owner=root group=root mode=0440
- name: Copia o tema de fundo
  copy: src=files/fundo.png dest=/home/mindmakers owner=root group=root mode=0440
- name: Copia arquivo de versão para SO em inglês
  copy: src=files/v2-0 dest=/home/pi/Desktop owner=root group=root mode=0440
  when: linguagem == "en"
- name: Copia arquivo de versão para SO em português
  copy: src=files/v2-0 dest=/home/pi/Área de Trabalho owner=root group=root mode=0440
  when: linguagem == "pt"
