- file:
    path: "/home/pi/Área de Trabalho"
    state: directory
    attributes: -i
    recurse: yes
- name: Copiando demais atalhos para a Área de Trabalho
  copy:
     src: files/headless/desktop/
     dest: "/home/pi/Área de Trabalho"
     owner: pi
     group: pi
     attributes: +i
     mode: 0755
