- name: Copia arquivos de imagens
  copy: src=files/icons dest=/usr/share mode=01777
- name: Copia programas executáveis
  copy: src=files/programs dest=/home/mindmakers mode=01777
- name: Copia a imagem tema de fundo
  copy: src=files/fundo.png dest=/home/mindmakers mode=01777
- name: Copia arquivo com notas de liberação da versão do disco
  copy: src=releasenotes.txt dest="/home/mindmakers" mode=01777  

