- name: Copia o atalho para notas de liberacão para o Desktop - SO em inglês
  copy: src=releasenotes.desktop dest=/home/pi/Desktop mode=0755
- name: Copia demais arquivos de atalho para o Desktop - SO em inglês
  copy: src=files/desktop/ dest=/home/pi/Desktop mode=0755 attributes=-i
#- name: Torna icones do Desktop imutáveis
#  shell: 'cd /home/pi/Desktop && sudo chattr +i 3DSlash.desktop makeblock.desktop releasenotes.desktop ativacao.desktop mblock.desktop scratch2.desktop capturafoto.desktop mindmakers.desktop sphero_desconecta.desktop codeorg.desktop mmblockly.desktop sphero.desktop gifpal.desktop pixlr.desktop update.desktop'
