- name: copy images
  copy: src=files/icons dest=/usr/share owner=root group=root mode=0440
- name: copy shortcuts
  copy: src=files/Desktop dest=/home/pi owner=root group=root mode=0440
- name: copy programs
  copy: src=files/programs dest=/home/mindmakers owner=root group=root mode=0440
