- name:         Criando pastas de configuração
  file:
    path:       /home/pi/.config/pcmanfm
    state:      directory
    mode:       0755
- file:
    path:       /home/pi/.config/pcmanfm/LXDE-pi
    state:      directory
    mode:       0755
- file:
    path:       /home/pi/.config/pcmanfm
    state:      directory
    attributes: -i
    recurse:    yes
- name:         Trocando imagem de fundo e posiciona icones padrões do Desktop
  copy:
     src:       files/headless/pcmanfm/LXDE-pi/desktop-items-0.conf
     dest:      /home/pi/.config/pcmanfm/LXDE-pi
     mode:      0755
- name:         Copiando a imagem tema de fundo
  copy:
     src:       files/headless/fundo.png
     dest:      /home/mindmakers
     mode:      0755
- name:         Alterando fundo.png para fundo-en.png
  lineinfile:
    path:       /home/pi/.config/pcmanfm/LXDE-pi/desktop-items-0.conf
    regexp:     '^wallpaper=/home/mindmakers/fundo.png'
    line:       'wallpaper=/home/mindmakers/fundo-en.png'
    backrefs:   yes
  when:         "'en_' in ansible_facts.env.LANGUAGE"
- shell:        'sudo bash /home/mindmakers/programs/shells/change-shortcut2.sh'
  args:
    warn:       no
