- name:         Criando pastas de configuração
  file:
    path:       /home/pi/.config/pcmanfm
    state:      directory
    mode:       0755
- file:
    path:       /home/pi/.config/pcmanfm/LXDE-pi
    state:      directory
    mode:       0755
- file:
    path:       /home/pi/.config/pcmanfm
    state:      directory
    attributes: -i
    recurse:    yes
- name:         Trocando imagem de fundo e posicionando ícones padrões do Desktop
  copy:
     src:       files/pcmanfm/LXDE-pi/desktop-items-0.conf
     dest:      /home/pi/.config/pcmanfm/LXDE-pi
     mode:      0755
- name:         Alterando fundo.png para fundo-en.png
  lineinfile:
    path:       /home/pi/.config/pcmanfm/LXDE-pi/desktop-items-0.conf
    regexp:     '^wallpaper=/home/mindmakers/fundo.png'
    line:       'wallpaper=/home/mindmakers/fundo-en.png'
    backrefs:   yes
  when:         "'en_' in ansible_facts.env.LANG"
- file:
    path:       /home/mindmakers/Scratch3
    state:      directory
    attributes: -i
    recurse:    yes
- name:         Copiando pasta Scratch3
  copy:
     src:       files/Scratch3
     dest:      /home/mindmakers
     owner:     pi
     group:     pi
     mode:      0755
- name:         Tornando ícones dentro da pasta Scratch3 imutáveis
  file:
    path:       /home/mindmakers/Scratch3
    state:      directory
    attributes: +i
    recurse:    yes
- shell:        'sudo bash /home/mindmakers/programs/shells/change-shortcut2.sh'
  args:
    warn:       no
- file:
    path:       /home/mindmakers/AppInventor
    state:      directory
    attributes: -i
    recurse:    yes
- name:         Copiando pasta App Inventor
  copy:
     src:       files/AppInventor
     dest:      /home/mindmakers
     owner:     pi
     group:     pi
     mode:      0755
- name:         Tornando itens dentro da pasta AppInventor imutáveis
  file:
    path:       /home/mindmakers/AppInventor
    state:      directory
    attributes: +i
    recurse:    yes
#- file:
#    path:      /home/pi/.config/pcmanfm/LXDE-pi/desktop-items-0.conf
#    state:     touch
#    attributes: +i
- file:
    path:          /home/mindmakers/Scratch2
    state:         directory
    attributes:    -i
    recurse:       yes
- name: Remove diretorio de projetos do Scratch2
  ansible.builtin.file:
    path: /home/mindmakers/Scratch2
    state: absent
- name: Remove atalho para executar o Scratch2
  ansible.builtin.file:
    path: /home/pi/Desktop/scratch2.desktop
    state: absent  
- name: check scratch2_folder.desktop that doesn't exist with state touch
  file:
    path: /home/pi/Desktop/scratch2_folder.desktop
    state: touch
- file:
    path: /home/pi/Desktop/scratch2_folder.desktop
    attributes:    -i
- name: Remove atalho de pastas para projetos Scratch2
  ansible.builtin.file:
    path: /home/pi/Desktop/scratch2_folder.desktop
    state: absent       
