- name: copy images
  copy: src=files/icons dest=/usr/share owner=root group=root mode=0440
- name: copy shortcuts
  copy: src=files/Desktop dest=/home/pi owner=root group=root mode=0440
- name: copy programs
  copy: src=files/programs dest=/home/mindmakers owner=root group=root mode=0440
- name: copy themes
  copy: src=files/fundo_v1.png dest=/mindmakers/images owner=root group=root mode=0440
- name: copy version
  copy: src=files/v2.0 dest=/home/pi/Desktop owner=root group=root mode=0440
