- name: Copia arquivos de imagens
  copy: src=files/icons dest=/usr/share mode=01777
- name: Sincroniza programas
  copy: src=files/programs dest=/home/mindmakers mode=01777
- name: Copia o tema de fundo
  copy: src=files/fundo.png dest=/home/mindmakers mode=01777

