- name: Copia arquivos de imagens
  copy: src=files/icons dest=/usr/share mode=01777
- name: Copia programas executáveis
  copy: src=files/programs dest=/home/mindmakers mode=01777
- name: Copia a imagem tema de fundo
  copy: src=files/fundo.png dest=/home/mindmakers mode=01777
- name: Copia icone de atualizao da image
  copy: src=files/desktop/update.desktop dest=/home/mindmakers mode=01777
- name: Copia arquivo com notas de liberação da versão do disco
  copy: src=releasenotes.txt dest=/home/mindmakers mode=01777
- name: Troca imagem de fundo e posiciona icones padrões do Desktop
  copy: src=files/desktop-items-0.conf dest=/home/pi/.config/pcmanfm/LXDE-pi mode=01777
- name: Personaliza barra superior
  copy: src=files/panel dest=/home/pi/.config/lxpanel/LXDE-pi/panels mode=01777
- name: Altera resolucao da tela
  copy: src=files/config.txt dest=/boot
- name: Verifica Versao npm
  hell: "pcmanfm --reconfigure"
