- name: Copia arquivo de versão da imagem de disco para SO em português
  copy: src=releasenotes.txt dest="/home/mindmakers" mode=01777
- name: Copia as notas de liberacão para a Área de Trabalho em português
  copy: src=releasenotes.desktop dest="/home/pi/Área de Trabalho" mode=01777
- name: Copia arquivos de atalhos para Área de Trabalho em português
  copy: src=files/desktop/ dest="/home/pi/Área de Trabalho" mode=01777

