- name:            Copiando arquivos de imagens
  copy:
     src:          files/icons
     dest:         /usr/share
     mode:         0777
- name:            Copiando programas executáveis
  copy:
     src:          files/programs
     dest:         /home/mindmakers
     mode:         0755
- name:            Verificando shell Sphero
  stat:
     path:         /home/mindmakers/programs/shells/sphero-connect.sh
  register:        sphero
- copy:
     src:          files/sphero-connect.sh
     dest:         /home/mindmakers/programs/shells/
     mode:         0755
  when:            not sphero.stat.exists
- copy:
     src:          files/sphero-connect-bolt.sh
     dest:         /home/mindmakers/programs/shells/
     mode:         0755
- file:
    path:          /home/pi/.config/lxpanel
    state:         directory
    attributes:    -i
    recurse:       yes
- name:            Personalizando barra superior
  copy:
     src:          files/panel
     dest:         /home/pi/.config/lxpanel/LXDE-pi/panels
     # attributes: +i
     mode:         0755
- name:            Personalizando configurações Desktop
  copy:
     src:          files/config/libfm
     dest:         /home/pi/.config/
     # attributes: +i
     mode:         0755
- name:            Alterando resolução da tela
  lineinfile:
    path:          /boot/config.txt
    regexp:        '^#hdmi_group=1'
    line:          'hdmi_group=2'
    backrefs:      yes
- lineinfile:
    path:          /boot/config.txt
    regexp:        '^#hdmi_mode=1'
    line:          'hdmi_mode=81'
    backrefs:      yes
- lineinfile:
    path:          /boot/config.txt
    regexp:        '^#hdmi_force_hotplug=1'
    line:          'hdmi_force_hotplug=1'
    backrefs:      yes
- lineinfile:
      path:        /boot/config.txt
      regexp:      'disable_splash=1'
      line:        'disable_splash=1'
      insertafter: EOF
- name:            Verificando se existe arquivo school.info
  stat:
     path:         /home/mindmakers/school.info
  register:        school
- copy:
     src:          school.info
     dest:         /home/mindmakers/school.info
     mode:         0755
  when:            not school.stat.exists
- file:
     path:         /usr/local/bin
     state:        directory
     mode:         0755
- file:
    path:          /usr/local/bin/alocar-para-escola.sh
    state:         absent
- file:
    path:          /usr/local/bin/alocar-para-instrutor.sh
    state:         absent
- copy:
     src:          files/bin
     dest:         /usr/local/
     mode:         0755
- copy:
     src:          files/programs/shells/adb-foto-download.sh
     dest:         /usr/local/bin
     mode:         0755
- name:            Copiando arquivo de inicialização do mqtt
  copy:
     src:          files/autostart/mqttbot
     dest:         /etc/init.d
     mode:         0755
- shell:           'sudo update-rc.d mqttbot defaults'
  args:
    warn:          no
- name:            Copiando arquivo de inicialização do mmiotjs
  copy:
     src:          files/autostart/mmiotjs
     dest:         /etc/init.d
     mode:         0755
- shell:           'sudo update-rc.d mmiotjs defaults'
  args:
    warn:          no
- stat:
     path:         /home/mindmakers/imgs/win.png
  register:        imgs
- name:            Copiando imagens
  copy:
     src:          files/imgs
     remote_src:   yes
     dest:         /home/mindmakers
     mode:         0755
- name:            Copiando imagens de apresentações da linha do tempo
  copy:
     src:          files/imgs/sala
     dest:         /home/mindmakers/imgs
     remote_src:   yes
     mode:         0755
- name:            Copiando arquivo de configuracao experimental para webbluetooth
  copy:
     src:          files/bluetooth.service
     dest:         /lib/systemd/system
     mode:         0755
- name:            Verificando se existe arquivos do MT3
  stat:
     path:         /home/pi/Documents/meus_arquivos/documentos/lembrete.txt
  register:        mt3files
- copy:
     src:          files/meus_arquivos_mt3
     dest:         /home/pi/Documents/
     mode:         0755
  when:            not mt3files.stat.exists     
     
