- name: Copia o atalho para notas de liberacão para a Área de Trabalho - SO em português
  copy:
     src: releasenotes.desktop
     dest: "/home/pi/Área de Trabalho"
     owner: pi
     group: pi
     attributes: +i
     mode: 0755
- name: Copia arquivo com notas de liberação da versão do disco
  copy:
     src: releasenotes.info
     dest: /home/mindmakers
     mode: 0755
