- name: Copia o atalho para notas de liberacão para o Desktop
  copy:
     src: releasenotes.desktop
     dest: /home/pi/Desktop
     owner: pi
     group: pi
     attributes: +i
     mode: 0755
- name: Copia arquivo com notas de liberação da versão do disco
  copy:
     src: releasenotes.info
     dest: /home/mindmakers
     mode: 0755
