- name: Instala Nodejs
  apt: name={{item}}
  with_items:
    - node=9.9.0
    - npm=6.1.0
- name: Instala pacote node.js "sphero"
  npm:
    name: sphero
    global: yes
- name: Instala pacote node.js "noble"
  npm:
    name: noble
    global: yes
- name: Instala pacote node.js "serialport"
  npm:
    name: serialport
    global: yes
