- name: Instala Nodejs
  apt: name={{item}}
  with_items:
    - node
    - npm
- name: Instala pacote node.js "sphero"
  npm:
    name: sphero
    global: yes
- name: Instala pacote node.js "noble"
  npm:
    name: noble
    global: yes
- name: Instala pacote node.js "serialport"
  npm:
    name: serialport
    global: yes
