- name: Instala Nodejs
  apt: name={{item}}
  with_items:
    - node
- name: Instala pacote node.js "sphero"
  npm:
    name: sphero
- name: Instala pacote node.js "noble"
  npm:
    name: noble
- name: Instala pacote node.js "serialport"
  npm:
    name: serialport
