- name: Instala Nodejs 10.15.3 e NPM 6.9.0 PPA
  shell: 'curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -'  
- name: Instala Nodejs 10.15.3 e NPM 6.9.0
  apt: name={{item}}
  with_items:
    - nodejs
    - build-essential  
- name: Instala pacote do nodejs "sphero"
  npm:
    name: sphero
    global: yes
- name: Instala pacote do nodejs "noble"
  npm:
    name: noble
    global: yes
- name: Instala pacote do nodejs "serialport"
  npm:
    name: serialport
    executable: /usr/bin/npm --unsafe-perm=true
    global: yes
