- name: Verificando se o Node.js já foi instalado
  stat:
     path: /home/mindmakers/programs/verify/node815
  register: nodejs
- name: Instalando Nodejs 8.15.3
  shell: 'curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -'
  when: not nodejs.stat.exists
- name: Instalando Nodejs 8.15.3
  apt:
     name: [nodejs]
  when: not nodejs.stat.exists
- name: Criando pasta de verificação de instalação do node 8.15.3
  file:
    path: /home/mindmakers/programs/verify/node815
    state: directory
    mode: 0444
- name: Instalando libudev-dev e build-essential
  apt:
     name: [libudev-dev, build-essential]
- name: Instalando vnstat
  apt:
     name: [vnstat]
- name: Atualizando a versão do Chromium-browser
  apt:
     name: chromium-browser=72*
- name: Verificando se o npm já foi instalado
  stat:
     path: /home/mindmakers/programs/verify/npm69
  register: npm
- name: Instalando npm 1.4.0
  apt:
     name: [npm]
  when: not npm.stat.exists
- name: Atualizando npm para 6.9.0
  npm: name={{item}} global=yes
  with_items:
    - npm
    - npm
  when: not npm.stat.exists
- name: Criando pasta de verificação de instalação do npm 6.9.0
  file:
    path: /home/mindmakers/programs/verify/npm69
    state: directory
    mode: 0444
- name: Verificando se as dependências npm do Sphero já foram instaladas
  stat:
     path: /home/mindmakers/programs/verify/npmsphero
  register: npmsphero
- name: Instalando pacote do npm "bluetooth-hci-socket"
  npm:
    name:  bluetooth-hci-socket
    path: /home/mindmakers/programs
    executable: /usr/bin/npm --unsafe-perm=true
  when: not npmsphero.stat.exists
- name: Instalando pacote do npm "bluebird"
  npm:
    name: bluebird
    path: /home/mindmakers/programs
  when: not npmsphero.stat.exists
- name: Instalando pacote do npm "browser-serialport"
  npm:
    name: browser-serialport
    path: /home/mindmakers/programs
  when: not npmsphero.stat.exists
- name: Instalando pacote do npm "debug"
  npm:
    name: debug
    path: /home/mindmakers/programs
  when: not npmsphero.stat.exists
- name: Instalando pacote do npm "express"
  npm:
    name: express
    path: /home/mindmakers/programs
  when: not npmsphero.stat.exists
- name: Instalando pacote do npm "grunt"
  npm:
    name: grunt
    path: /home/mindmakers/programs
  when: not npmsphero.stat.exists
- name: Instalando pacote do npm "keypress"
  npm:
    name: keypress
    path: /home/mindmakers/programs
  when: not npmsphero.stat.exists
- name: Instalando pacote do npm "webworker-threads"
  npm:
    name: webworker-threads
    path: /home/mindmakers/programs
    executable: /usr/bin/npm --unsafe-perm=true
  when: not npmsphero.stat.exists
- name: Instalando pacote do npm "noble"
  npm:
    name: noble
    path: /home/mindmakers/programs
    executable: /usr/bin/npm --unsafe-perm=true
  when: not npmsphero.stat.exists
- name: Instalando pacote do npm "sphero"
  npm:
    name: sphero
    path: /home/mindmakers/programs
  when: not npmsphero.stat.exists
- name: Instalando pacote do npm "serialport"
  npm:
    name: serialport
    path: /home/mindmakers/programs
    executable: /usr/bin/npm --unsafe-perm=true
  when: not npmsphero.stat.exists
- name: Instalando pacote do npm "request"
  npm:
    name: request
    path: /home/mindmakers/programs
  when: not npmsphero.stat.exists
- name: Instalando pacote do npm "inquirer"
  npm:
    name: inquirer
    path: /home/mindmakers/programs
  when: not npmsphero.stat.exists
- name: Criando pasta de verificação das dependências Sphero
  file:
    path: /home/mindmakers/programs/verify/npmsphero
    state: directory
    mode: 0444
