- name: Clona modulo requests para Python.
  git:
    repo: 'https://github.com/requests/requests.git'
    dest: /home/mindmakers/programs/requests
    clone: yes
    
- name: Instala Nodejs 8.15.3
  shell: 'cd /home/mindmakers/programs/requests && sudo pip install .' 
