- name:            Verificando se as configurações de som ja foram alteradas
  stat:
     path:         /home/mindmakers/programs/verify/alterasom
  register:        alterasom
- name:            Alterando configuracao de som para analog
  copy:
     src:          files/.asoundrc
     dest:         /home/pi/
     mode:         0644
  when:          not alterasom.stat.exists
- name:            Criando pasta de verificação da alteração de configuração de som
  file:
    path:          /home/mindmakers/programs/verify/alterasom
    state:         directory
    mode:          0444
