- name: Copiando a imagem tema de fundo
  copy:
     src: files/fundo.png
     dest: /home/mindmakers
     mode: 0755
- name: Copiando a imagem tema de fundo
  copy:
     src: files/fundo-en.png
     dest: /home/mindmakers
     mode: 0755
- file:
    path: "/home/pi/Área de Trabalho"
    state: directory
    attributes: -i
    recurse: yes
- file:
    path: "/home/pi/Área de Trabalho/sphero_disconnect.desktop"
    state: absent
- name: Copiando update.desktop para o Desktop
  copy:
     src: files/update.desktop
     dest: "/home/pi/Área de Trabalho/"
     owner: pi
     group: pi
     attributes: +i
     mode: 0755
- file:
    path: "/home/pi/Área de Trabalho/mblock.desktop"
    state: absent
- file:
    path: /home/mindmakers/Scratch2
    state: directory
    attributes: -i
    recurse: yes
- file:
    path: /home/mindmakers/Scratch2/portuguese/Gabaritos
    state: absent
- file:
    path: /home/mindmakers/Scratch2/english/Answer-Sheet
    state: absent
- file:
    path: /home/mindmakers/Scratch2
    state: directory
    attributes: +i
    recurse: yes
- name: Copiando demais atalhos para a Área de Trabalho
  copy:
     src: files/desktop/
     dest: "/home/pi/Área de Trabalho"
     owner: pi
     group: pi
     attributes: +i
     mode: 0755
- name: Verificando ícone mindmakers.desktop na Área de Trabalho
  stat:
     path: "/home/pi/Área de Trabalho/mindmakers.desktop"
  register: mmdesk
- name: Copiando atalho mindmakers.desktop para a Área de Trabalho
  copy:
     src: files/mindmakers.desktop
     dest: "/home/pi/Área de Trabalho"
     owner: pi
     group: pi
     mode: 0755
  when: not mmdesk.stat.exists
- name: Verificando ícone sphero.desktop
  stat:
     path: "/home/pi/Área de Trabalho/sphero.desktop"
  register: spherodesk
- name: Copiando atalho sphero.desktop
  copy:
     src: files/sphero.desktop
     dest: "/home/pi/Área de Trabalho/sphero.desktop"
     owner: pi
     group: pi
     mode: 0755
  when: not spherodesk.stat.exists
- name: Verificando OS em inglês
  shell: 'cat /etc/default/locale | grep LANG= '
  args:
    warn: no
  register: lang
- file:
    path: "/home/pi/Área de Trabalho/scratch2_folder.desktop"
    state: touch
    attributes: -i
  when: lang.stdout.find('LANG=en') != -1
- name: Alterando atalho da pasta Scratch2
  lineinfile:
    path: "/home/pi/Área de Trabalho/scratch2_folder.desktop"
    regexp: '^Exec=pcmanfm /home/mindmakers/Scratch2/portuguese'
    line: 'Exec=pcmanfm /home/mindmakers/Scratch2/english'
    backrefs: yes
  when: lang.stdout.find('LANG=en') != -1
# - file:
#     path: "/home/pi/Área de Trabalho/scratch2_folder.desktop"
#     state: touch
#     attributes: +i
- file:
    path: /home/pi/Scratch2
    state: absent
- shell: 'sudo ln -s /home/mindmakers/Scratch2/english /home/pi/Scratch2'
  args:
    warn: no
  when: lang.stdout.find('LANG=en') != -1
- shell: 'sudo ln -s /home/mindmakers/Scratch2/portuguese /home/pi/Scratch2'
  args:
    warn: no
  when: lang.stdout.find('LANG=pt') != -1
- file:
    path: /home/pi/Fotos
    state: absent
- file:
    path: /home/pi/Pictures/Pictures
    state: absent
- file:
    path: /home/pi/Pictures/Fotos
    state: absent
- shell: 'sudo ln -s /home/pi/Pictures /home/pi/Fotos'
  args:
    warn: no
  when: lang.stdout.find('LANG=pt') != -1
