- name: Copiando a imagem tema de fundo
  copy:
     src: files/fundo.png
     dest: /home/mindmakers
     mode: 0755
- name: Copiando a imagem tema de fundo
  copy:
     src: files/fundo-en.png
     dest: /home/mindmakers
     mode: 0755
- file:
    path: "/home/pi/Área de Trabalho"
    state: directory
    attributes: -i
    recurse: yes
- file:
    path: "/home/pi/Área de Trabalho/sphero_disconnect.desktop"
    state: absent
- name: Copiando update.desktop para o Desktop
  copy:
     src: files/update.desktop
     dest: "/home/pi/Área de Trabalho/"
     owner: pi
     group: pi
     attributes: +i
     mode: 0755
- file:
    path: "/home/pi/Área de Trabalho/mblock.desktop"
    state: absent
- name: Copiando demais atalhos para a Área de Trabalho
  copy:
     src: files/desktop/
     dest: "/home/pi/Área de Trabalho"
     owner: pi
     group: pi
     attributes: +i
     mode: 0755
- name: Verificando ícone mindmakers.desktop na Área de Trabalho
  stat:
     path: "/home/pi/Área de Trabalho/mindmakers.desktop"
  register: mmdesk
- name: Copiando atalho mindmakers.desktop para a Área de Trabalho
  copy:
     src: files/mindmakers.desktop
     dest: "/home/pi/Área de Trabalho"
     owner: pi
     group: pi
     attributes: +i
     mode: 0755
  when: not mmdesk.stat.exists
- name: Verificando ícone sphero.desktop
  stat:
     path: "/home/pi/Área de Trabalho/sphero.desktop"
  register: spherodesk
- copy:
     src: files/sphero.desktop
     dest: "/home/pi/Área de Trabalho/sphero.desktop"
     owner: pi
     group: pi
     attributes: +i
     mode: 0755
  #when: not spherodesk.stat.exists
- name: Verificando ícone activate.desktop
  stat:
     path: "/home/pi/Área de Trabalho/activate.desktop"
  register: activatedesk
- copy:
     src: files/activate.desktop
     dest: "/home/pi/Área de Trabalho/activate.desktop"
     owner: pi
     group: pi
     attributes: +i
     mode: 0755
  when: not activatedesk.stat.exists
- name: Verificando ícone classroom_test.desktop
  stat:
     path: "/home/pi/Área de Trabalho/classroom_test.desktop"
  register: classroom_testdesk
- copy:
     src: files/classroom_test.desktop
     dest: "/home/pi/Área de Trabalho/classroom_test.desktop"
     owner: pi
     group: pi
     attributes: +i
     mode: 0755
  when: not classroom_testdesk.stat.exists
# - name:
#   shell: 'sudo chattr -i /home/pi/Desktop/scratch2_folder.desktop'
#   args:
#     warn: no
#   when: "'en_' in ansible_facts.env.LANGUAGE"
# - file:
#     path: "/home/pi/Área de Trabalho/scratch2_folder.desktop"
#     state: touch
#     attributes: -i
#   when: "'en_' in ansible_facts.env.LANGUAGE"
# - name: Alterando atalho da pasta Scratch2
#   lineinfile:
#     path: "/home/pi/Área de Trabalho/scratch2_folder.desktop"
#     regexp: '^Exec=pcmanfm /home/mindmakers/Scratch2/portuguese'
#     line: 'Exec=pcmanfm /home/mindmakers/Scratch2/english'
#     backrefs: yes
#   when: "'en_' in ansible_facts.env.LANGUAGE"
# - name:
#   shell: 'sudo chattr +i /home/pi/Desktop/scratch2_folder.desktop'
#   args:
#     warn: no
#   when: "'en_' in ansible_facts.env.LANGUAGE"
# - file:
#     path: "/home/pi/Área de Trabalho/scratch2_folder.desktop"
#     state: touch
#     attributes: +i
- file:
    path: /home/pi/Scratch2
    state: absent
# - shell: 'sudo ln -s /home/mindmakers/Scratch2/english /home/pi/Scratch2'
#   args:
#     warn: no
#   when: "'en_' in ansible_facts.env.LANGUAGE"
# - shell: 'sudo ln -s /home/mindmakers/Scratch2/portuguese /home/pi/Scratch2'
#   args:
#     warn: no
#   when: "'pt_BR' in ansible_facts.env.LANGUAGE"
- file:
    path: /home/pi/Fotos
    state: absent
- file:
    path: /home/pi/Pictures/Pictures
    state: absent
- file:
    path: /home/pi/Pictures/Fotos
    state: absent
- shell: 'sudo ln -s /home/pi/Pictures /home/pi/Fotos'
  args:
    warn: no
  when: "'pt_BR' in ansible_facts.env.LANGUAGE"
