- name: Copiando a imagem tema de fundo
  copy:
     src: files/teacher/fundo.png
     dest: /home/mindmakers
     mode: 0755
- name: Copiando a imagem tema de fundo
  copy:
     src: files/teacher/fundo-en.png
     dest: /home/mindmakers
     mode: 0755
- file:
    path: "/home/pi/Área de Trabalho"
    state: directory
    attributes: -i
    recurse: yes
- file:
    path: "/home/pi/Área de Trabalho/sphero_disconnect.desktop"
    state: absent
- name: Verificando ícone mindmakers.desktop
  stat:
     path: "/home/pi/Área de Trabalho/mindmakers.desktop"
  register: mmdesk
- name: Copiando atalho mindmakers.desktop versão de professor
  copy:
     src: files/teacher/mindmakers.desktop
     dest: "/home/pi/Área de Trabalho/mindmakers.desktop"
     owner: pi
     group: pi
     attributes: +i
     mode: 0755
  when: not mmdesk.stat.exists
- name: Copiando versão de professor do update.desktop
  copy:
     src: files/teacher/update.desktop
     dest:  "/home/pi/Área de Trabalho"
     owner: pi
     group: pi
     attributes: +i
     mode: 0755
- name: Verificando ícone sphero.desktop
  stat:
     path: "/home/pi/Área de Trabalho/sphero.desktop"
  register: spherodesk
- name: Copiando atalho sphero.desktop
  copy:
     src: files/sphero.desktop
     dest: "/home/pi/Área de Trabalho/sphero.desktop"
     owner: pi
     group: pi
     attributes: +i
     mode: 0755
#  when: not spherodesk.stat.exists
- name: Verificando ícone activate.desktop
  stat:
     path: "/home/pi/Área de Trabalho/activate.desktop"
  register: activatedesk
- copy:
     src: files/activate.desktop
     dest: "/home/pi/Área de Trabalho/activate.desktop"
     owner: pi
     group: pi
     attributes: +i
     mode: 0755
  when: not activatedesk.stat.exists
- name: Verificando ícone classroom_test.desktop
  stat:
     path: "/home/pi/Área de Trabalho/classroom_test.desktop"
  register: classroom_testdesk
- copy:
     src: files/classroom_test.desktop
     dest: "/home/pi/Área de Trabalho/classroom_test.desktop"
     owner: pi
     group: pi
     attributes: +i
     mode: 0755
  when: not classroom_testdesk.stat.exists
#############
- name: Copiando demais atalhos para a Área de Trabalho
  copy:
     src: files/desktop/
     dest: "/home/pi/Área de Trabalho"
     owner: pi
     group: pi
     attributes: +i
     mode: 0755
- file:
    path: /usr/local/bin/alocar-para-instrutor.sh
    state: touch
    attributes: -i
- file:
    path: /usr/local/bin/alocar-para-instrutor.sh
    state: absent
# - file:
#     path: "/home/pi/Área de Trabalho/scratch2_folder.desktop"
#     state: touch
#     attributes: +i
- file:
    path: /home/pi/Fotos
    state: absent
- file:
    path: /home/pi/Pictures/Pictures
    state: absent
- file:
    path: /home/pi/Pictures/Fotos
    state: absent
- shell: 'sudo ln -s /home/pi/Pictures /home/pi/Fotos'
  args:
    warn: no
  when: "'pt_BR' in ansible_facts.env.LANGUAGE"
