- name: Verificando ícone mindmakers.desktop
  stat:
     path: "/home/pi/Área de Trabalho/mindmakers.desktop"
  register: mmdesk
- name: Copiando atalho mindmakers.desktop versão de professor
  copy:
     src: files/teacher/mindmakers.desktop
     dest: "/home/pi/Área de Trabalho/mindmakers.desktop"
     owner: pi
     group: pi
     mode: 0755
  when: not mmdesk.stat.exists
- file:
    path: "/home/pi/Área de Trabalho/update.desktop"
    state: touch
    attributes: -i
- name: Copiando versão de professor do update.desktop
  copy:
     src: files/teacher/update.desktop
     dest:  "/home/pi/Área de Trabalho"
     owner: pi
     group: pi
     attributes: +i
     mode: 0755
