- name:     Instalando pacote do npm "cors"
  npm:
    name:   cors
    # version: '4.1.1'
    path:   /home/mindmakers/programs
# - name:   Instalando xterm
#   apt:
#      name: xterm
- name:     Desinstalando aplicações não utilizadas
  apt:
     name:  xterm
     state: absent
     purge: yes
- name:     Instalando IDE Arduino
  apt:
     name:  arduino
- name:     Instalando python3-pip
  apt:
     name:  python3-pip
- name:     Instalando s3-extend
  shell:    'sudo pip3 install -U s3-extend'
  args:
    warn:   no

# - name:   Copiando arquivo de inicialização do s3r
#   copy:
#      src: files/arduino/s3_extend
#      dest: /usr/local/lib/python3.7/dist-packages/
#      owner: root
#      group: staff
#      mode: 0644

- name:     Copiando arquivo de inicialização do s3r
  copy:
     src:   files/autostart/mmgpio
     dest:  /etc/init.d
     mode:  0755
- name:     Configurando reinicio automático do serviço mmgpio
  copy:
     src:   files/autostart/mmgpio.service.d
     dest:  /etc/systemd/system
     mode:  0755
- shell:    'sudo update-rc.d mmgpio defaults'
  args:
    warn:   no
- shell:    'sudo systemctl daemon-reload'
  args:
    warn:   no
- name:     update chomium
  apt:
    name:   chromium-browser
    state:  latest

- name:     Instalando pigpio
  apt:
     name:  [pigpio, pigpiod]
     state: latest

- name:     copiando arquivos sketchbook
  copy:
     src:   files/arduino/sketchbook
     dest:  /home/pi/
     owner: pi
     group: pi
     mode:  0755
- name:     Criando pastas de sketchbook
  file:
    path:   /home/pi/.arduino
    state:  directory
    mode:   0755
- name:     copiando arquivos sketchbook
  copy:
     src:   files/arduino/preferences.txt
     dest:  /home/pi/.arduino
     owner: pi
     group: pi
     mode:  0755
