- name: Atualizando pacotes 1
  apt:
    name:
      [
        ffmpeg,
        file,
        firmware-atheros,
        firmware-brcm80211,
        firmware-libertas,
        firmware-misc-nonfree,
        firmware-realtek,
        gtk2-engines-pixflat,
        libarchive13,
        libavcodec58,
        libavdevice58,
        libavfilter7,
        libavformat58,
        libavresample4,
        libavutil56,
        libbabeltrace1,
        libblockdev-fs2,
        libblockdev-loop2,
        libblockdev-part-err2,
        libblockdev-part2,
        libblockdev-swap2,
        libblockdev-utils2,
        libblockdev2,
        libbz2-1.0,
        libcom-err2,
        libcryptsetup12,
        libcups2,
        libcupsimage2,
      ]
    state: latest
- name: Atualizando pacotes 2
  apt:
    name:
      [
        libdrm-common,
        libdrm-etnaviv1,
        libdrm-nouveau2,
        libdrm-radeon1,
        libdrm2,
        libegl-mesa0,
        libexpat1-dev,
        libexpat1,
        libext2fs2,
        libfm-data,
        libfm-extra4,
        libfm-gtk-data,
        libfm-gtk4,
        libfm-modules,
        libfm4,
        libfreetype6-dev,
        libfreetype6,
        libfribidi0,
        libgbm1,
        libgl1-mesa-dri,
        libglapi-mesa,
        libgles2-mesa,
        libglib2.0-0,
        libglib2.0-bin,
        libglib2.0-data,
        libglx-mesa0,
        libjavascriptcoregtk-4.0-18,
        libldap-2.4-2,
        libldap-common,
        liblua5.2-0,
        libmagic-mgc,
      ]
    state: latest
- name: Atualizando pacotes 3
  apt:
    name:
      [
        libmagic1,
        libmp3lame0,
        libmtdev1,
        libncurses5,
        libncurses6,
        libncursesw5,
        libncursesw6,
        libnghttp2-14,
        libnss3,
        libobrender32v5,
        libobt2v5,
        libogg0,
        libpam-systemd,
        libpango-1.0-0,
        libpangocairo-1.0-0,
        libpangoft2-1.0-0,
        libpangoxft-1.0-0,
        libpostproc55,
        libpq5,
        libpulse0,
        libpython2.7-dev,
        libpython2.7-minimal,
        libpython2.7-stdlib,
        libpython2.7,
        libraspberrypi-bin,
        libraspberrypi-dev,
        libraspberrypi-doc,
        libraspberrypi0,
        libraw1394-11,
        libruby2.5,
      ]
    state: latest
- name: Atualizando pacotes 4
  apt:
    name:
      [
        libsasl2-2,
        libsasl2-modules-db,
        libscsynth1,
        libsdl-image1.2,
        libsmbclient,
        libsord-0-0,
        libspeex1,
        libspeexdsp1,
        libss2,
        libssl1.1,
        libswresample3,
        libswscale5,
        libsystemd0,
        libtiff5,
        libtinfo5,
        libtinfo6,
        libvlc-bin,
        libvlc5,
        libvlccore9,
        libvpx5,
        libwbclient0,
        libwebkit2gtk-4.0-37,
        libxaw7,
        libxcb-util0,
        libxdamage1,
        libxml2,
        libxmu6,
        libxmuu1,
        libxslt1.1,
        libxt-dev,
        libxt6,
        mesa-va-drivers,
        mesa-vdpau-drivers,
      ]
    state: latest
- name: Atualizando pacotes 5
  apt:
    name:
      [
        pi-bluetooth,
        pimixer,
        pipanel,
        pishutdown,
        piwiz,
        python3-piglow,
        python3-pigpio,
        python3-rpi.gpio,
        raspberrypi-bootloader,
        raspberrypi-kernel,
        raspberrypi-net-mods,
        raspberrypi-sys-mods,
        raspberrypi-ui-mods,
        raspi-config,
        raspi-gpio,
        rc-gui,
        rpi-chromium-mods,
        sc3-plugins-server,
        systemd-sysv,
        systemd,
      ]
    state: latest
- name: Atualizando pacotes 6
  apt:
    name:
      [
        pi-greeter,
        pi-package-data,
        pi-package-session,
        pi-package,
        libapt-inst2.0,
        libapt-pkg5.0,
        libbind9-161,
        libbinutils,
        libbluetooth3,
        libboost-atomic1.67.0,
        libboost-chrono1.67.0,
        libboost-date-time1.67.0,
        libboost-filesystem1.67.0,
        libboost-iostreams1.67.0,
        libboost-locale1.67.0,
        libboost-system1.67.0,
        libboost-thread1.67.0,
        libcurl3-gnutls,
        libcurl4,
        libdevmapper1.02.1,
        libdns-export1104,
        libdns1104,
        libegl1-mesa-dev,
        libegl1,
        libel-api-java,
        libexif12,
        libfuse2,
        libgl1-mesa-dev,
        libgl1,
        libgles1,
        libgles2-mesa-dev,
        libgles2,
        libglvnd-core-dev,
        libglvnd-dev,
        libglvnd0,
        libglx0,
        libgnutls30,
        libgs9-common,
        libgs9,
        libgssapi-krb5-2,
        libibus-1.0-5,
        libibus-1.0-dev,
        libicu63,
        libidn2-0,
        libimobiledevice6,
        libisc-export1100,
        libisc1100,
        libisccc161,
        libisccfg163,
        libjsp-api-java,
        libk5crypto3,
        libkrb5-3,
        libkrb5support0,
        liblog4j1.2-java,
        liblwres161,
        libmagickcore-6.q16-6-extra,
        libmagickcore-6.q16-6,
        libmagickwand-6.q16-6,
        libmatroska6v5,
        libmysofa0,
        libopengl0,
        libopenjp2-7,
        libopenmpt-modplug1,
        libopenmpt0,
        libpam-chksshpwd,
        libpam-modules-bin,
        libpam-modules,
        libpam-runtime,
        libpam0g,
        libpaper-utils,
        libpaper1,
        libpython3.7-dev,
        libpython3.7-minimal,
        libpython3.7-stdlib,
        libpython3.7,
        libqscintilla2-qt5-13,
        libqscintilla2-qt5-l10n,
        libqt5concurrent5,
        libqt5core5a,
        libqt5dbus5,
        libqt5gui5,
        libqt5network5,
        libqt5printsupport5,
        libqt5sql5-sqlite,
        libqt5sql5,
        libqt5test5,
        libqt5widgets5,
        libqt5xml5,
        libssh-gcrypt-4,
        libtag1v5-vanilla,
        libtag1v5,
        libtimedate-perl,
        libudev-dev,
        libudev1,
        libwebsocket-api-java,
        libzmq5,
        lua5.1,
        lxappearance-obconf,
        lxinput,
        lxplug-bluetooth,
        lxplug-cputemp,
        lxplug-ejecter,
        lxplug-network,
        lxplug-ptbatt,
        lxplug-volume,
        lxterminal,
      ]
    state: latest
#pacotes que não foram atualizados em 27-07-20 mas poderiam ser
# - name: Atualizando pacotes 7
#   apt:
#     name:
#       [
#         mesa-common-dev,
#         nano,
#         obconf,
#         omxplayer,
#         openbox,
#         patch,
#         pcmanfm,
#         pi-greeter,
#         pi-package-data,
#         pi-package-session,
#         pi-package,
#         scratch2,
#         sense-emu-tools,
#         sonic-pi-samples,
#         sonic-pi-server,
#         sonic-pi,
#         ssh,
#         sudo,
#         supercollider-server,
#         tzdata,
#         udev,
#         uno-libs3,
#         unzip,
#         ure,
#         usb.ids,
#         wpasupplicant,
#         x11-xserver-utils,
#         xdg-utils,
#         xserver-common,
#         xserver-xorg-core,
#       ]
#     state: latest
# - name: Atualizando pacotes 8
#   apt:
#     name:
#       [
#         android-sdk-platform-tools-common,
#         apt-transport-https,
#         apt-utils,
#         apt,
#         base-files,
#         bind9-host,
#         binutils-arm-linux-gnueabihf,
#         binutils-common,
#         binutils,
#         bluez-firmware,
#         bluez,
#         ca-certificates,
#         console-setup-linux,
#         console-setup,
#         cron,
#         curl,
#         dhcpcd5,
#         dirmngr,
#         distro-info-data,
#         dmsetup,
#         dphys-swapfile,
#         epiphany-browser-data,
#         epiphany-browser,
#         fonts-opensymbol,
#         freetype2-doc,
#         fuse,
#         ghostscript,
#         gir1.2-ibus-1.0,
#         gir1.2-pango-1.0,
#         git-man,
#         git,
#         gldriver-test,
#         gnupg-l10n,
#         gnupg-utils,
#         gnupg,
#         gnuplot-data,
#         gnuplot-qt,
#         gnuplot,
#         gpg-agent,
#         gpg-wks-client,
#         gpg-wks-server,
#         gpg,
#         gpgconf,
#         gpgsm,
#         gpgv,
#         gstreamer1.0-plugins-good,
#         gtk2-engines-clearlookspix,
#         imagemagick-6-common,
#         imagemagick-6.q16,
#         imagemagick,
#         initramfs-tools-core,
#         initramfs-tools,
#         iputils-ping,
#         keyboard-configuration,
#       ]
#     state: latest
