# Verifica se school.info ainda tem Pi não registrado para. true se não tiver e false se tiver.
- name: Ver se máquina já foi ativada para realizar a atualização de versão da plataforma.
  find:
     paths: /home/mindmakers/
     patterns: 'school.info'
     contains: 'Pi: Não'
     use_regex: yes
  register: semregistro

- name: Executando version_update.js
  command: nodejs mmversionupdate.js
  args:
    chdir: /home/mindmakers/programs
  when: semregistro.matched == 0
