- file:
     path: /home/pi/.config/autostart
     state: directory
     mode: 0755
- name: Instalando x11vnc
  apt:
     name: x11vnc
# - name: Copiando autostart
#   copy:
#      src: ongoing/autostart
#      dest: /home/pi/.config/
#      mode: 0777
- name: Copiando arquivo vncserver
  copy:
     src: files/tightvncserver
     dest: /etc/init.d
     mode: 0755
#  when: deb_check.stdout.find('<nenhuma>') != -1 or deb_check.stdout.find('<none>') != -1
- name: Configurando VncServer
  shell: 'sudo update-rc.d tightvncserver defaults'
  args:
    warn: no
